<div id="container" class="container-fluid">
    <salic-proposta idpreprojeto="<?= $this->idPreProjeto; ?>"></salic-proposta>
</div>

<script type="text/x-template" id="propostas">
    <div>
        <salic-proposta-identificacao :idpreprojeto="idpreprojeto" :proposta="dados"></salic-proposta-identificacao>
        <ul class="collapsible" data-collapsible="accordion">
            <li>
                <div class="collapsible-header"><i class="material-icons">history</i>Hist&oacute;rico</div>
                <div class="collapsible-body padding20">
                    <salic-proposta-historico-avaliacoes :idpreprojeto="dados.idPreProjeto"
                                                         v-bind:proposta="dados"></salic-proposta-historico-avaliacoes>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">person</i>Proponente</div>
                <div class="collapsible-body padding20">
                    <salic-agente-proponente :idagente="dados.idAgente"></salic-agente-proponente>
                    <salic-agente-usuario :idusuario="dados.idUsuario"></salic-agente-usuario>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">attachment</i>Documentos anexados</div>
                <div class="collapsible-body padding20">
                    <salic-proposta-documentos :proposta="dados"></salic-proposta-documentos>
                </div>
            </li>
            <li>
                <div id="plano-distribuicao" class="collapsible-header"><i class="material-icons">equalizer</i>Plano
                    Distribui&ccedil;&atilde;o
                </div>
                <div class="collapsible-body padding20">
                    <div id="html-plano-distribuicao"></div>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">history</i>Fonte de Recurso</div>
                <div class="collapsible-body padding20">
                    <!--                    <salic-proposta-fontes-de-recursos :idpreprojeto="idpreprojeto"></salic-proposta-fontes-de-recursos>-->
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">place</i>Local de realiza&ccedil;&atilde;o/Deslocamento
                </div>
                <div class="collapsible-body padding20">
                    <salic-proposta-local-realizacao-deslocamento
                        :idpreprojeto="idpreprojeto"></salic-proposta-local-realizacao-deslocamento>
                </div>
            </li>
            <li>
                <div id="planilha-orcamentaria" class="collapsible-header"><i class="material-icons">attach_money</i>Planilha
                    or&ccedil;ament&aacute;ria
                </div>
                <div class="collapsible-body padding20">
                    <div id="planilhaOrcamentariaMontada"></div>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Ficha t&eacute;cnica</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.FichaTecnica"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Resumo</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.ResumoDoProjeto"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Objetivos</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.Objetivos"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Etapa de Trabalho</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.EtapaDeTrabalho"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Acessibilidade</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.Acessibilidade"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Especifica&ccedil;&otilde;es t&eacute;cnicas
                    do produto
                </div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.Sinopse"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Sinopse de Obra</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.EspecificacaoTecnica"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Impacto Ambiental</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.ImpactoAmbiental"></salic-texto-simples>
                </div>
            </li>
            <li>
                <div class="collapsible-header"><i class="material-icons">subject</i>Justificativa</div>
                <div class="collapsible-body padding20" v-if="dados">
                    <salic-texto-simples :texto="dados.Justificativa"></salic-texto-simples>
                </div>
            </li>
        </ul>
    </div>
</script>

<script type="text/x-template" id="identificacao-da-proposta">
    <div class="dados-basicos" v-if="proposta">
        <div class="card">
            <div class="card-content">
                <h5>Identifica&ccedil;&atilde;o</h5>
                <div class="row">
                    <div class="col s12 l3 m3">
                        <b>Nº da proposta</b><br>
                        {{ proposta.idPreProjeto }}
                    </div>
                    <div class="col s12 l3 m6">
                        <b>Nome Projeto</b><br>
                        {{ proposta.NomeProjeto }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>Pronac</b><br>
                        {{ proposta.PRONAC }}
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 l3 m3">
                        <b>CNPJ/CPF</b><br>
                        {{ proposta.CNPJCPF }}
                    </div>
                    <div class="col s12 l6 m6">
                        <b>Proponente</b><br>
                        {{ proposta.NomeAgente }}
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Informa&ccedil;&otilde;es complementares</h5>
                <div class="row">
                    <div class="col s12 l3 m3">
                        <b>Mecanismo</b><br>
                        {{ Mecanismo }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>In&iacute;cio Execu&ccedil;&atilde;o</b><br>
                        {{ DtInicioDeExecucao }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>Final Execu&ccedil;&atilde;o</b><br>
                        {{ DtFinalDeExecucao }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>Dt. Fixa</b><br>
                        {{ stDataFixa }}
                    </div>
                </div>
                <div class="divider"></div>
                <div class="row">
                    <div class="col s12 l3 m3">
                        <b>Ag&ecirc;ncia banc&aacute;ria</b><br>
                        {{ proposta.AgenciaBancaria }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>É proposta audiovisual</b><br>
                        {{ AreaAbrangencia }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>Prorroga&ccedil;&atilde;o autom&aacute;tica</b><br>
                        {{ tpProrrogacao }}
                    </div>
                    <div class="col s12 l3 m3">
                        <b>Tipo de execu&ccedil;&atilde;o</b><br>
                        {{ proposta.TipoExecucao }}
                    </div>
                </div>
            </div>
        </div>
        <div v-if="proposta.NrAtoTombamento && proposta.NrAtoTombamento.length > 1" class="card">
            <div class="card-content">
                <h5>Tombamento</h5>
                <div class="row">
                    <div class="col s12 l4 m4">
                        <b>Nº Ato</b><br>
                        {{ proposta.NrAtoTombamento }}
                    </div>
                    <div class="col s12 l4 m4">
                        <b>Dt. Ato</b><br>
                        {{ DtAtoTombamento }}
                    </div>
                    <div class="col s12 l4 m4">
                        <b>Esfera</b><br>
                        {{ EsferaTombamento }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/x-template" id="tabela-simples">
    <div class="tabelas">
        <div class="row">
            <salic-table-easy v-bind:dados="dado"></salic-table-easy>
        </div>
    </div>
</script>

<script type="text/x-template" id="dados-proponente">
    <div id="proponente" v-if="proponente">

        <div v-if="identificacao" class="card">
            <div class="card-content">
                <h5>Identifica&ccedil;&atilde;o</h5>

                <div class="row">
                    <div class="col s12 l4 m4">
                        <b>CNPJ/CPF</b><br>
                        {{ identificacao.cnpjcpf }}
                    </div>
                    <div class="col s12 l4 m4">
                        <b>Nome Proponente</b><br>
                        {{ identificacao.descricao }}
                    </div>
                    <div class="col s12 l4 m4">
                        <b>Tipo de Pessoa</b><br>
                        {{ TipoPessoa }}
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Endere&ccedil;o</h5>
                <table v-if="proponente.enderecos" class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Tipo de Endere&ccedil;o</th>
                        <th>Tipo do Logradouro</th>
                        <th>Logradouro</th>
                        <th>N&uacute;mero</th>
                        <th>Complemento</th>
                        <th>Bairro</th>
                        <th>Cidade</th>
                        <th>UF</th>
                        <th>CEP</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="endereco in proponente.enderecos">
                        <td>{{ endereco.tipoendereco }}</td>
                        <td>{{ endereco.dstipologradouro }}</td>
                        <td>{{ endereco.logradouro }}</td>
                        <td>{{ endereco.numero }}</td>
                        <td>{{ endereco.complemento }}</td>
                        <td>{{ endereco.bairro }}</td>
                        <td>{{ endereco.municipio }}</td>
                        <td>{{ endereco.uf }}</td>
                        <td>{{ endereco.cep }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Telefones</h5>
                <table v-if="proponente.telefones" class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>UF</th>
                        <th>DDD</th>
                        <th>N&uacute;mero</th>
                        <th>Pode Divulgar?</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="telefone in proponente.telefones">
                        <td>{{ telefone.dstelefone }}</td>
                        <td>{{ telefone.ufsigla }}</td>
                        <td>{{ telefone.ddd }}</td>
                        <td>{{ telefone.numero }}</td>
                        <td>{{ label_sim_ou_nao(telefone.divulgar) }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>E-mail</h5>
                <table v-if="proponente.emails" class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>E-mail</th>
                        <th>Pode divulgar?</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="email in proponente.emails">
                        <td nowrap>{{ email.tipo }}</td>
                        <td nowrap>{{ email.descricao }}</td>
                        <td>{{ label_sim_ou_nao(email.divulgar) }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Natureza</h5>
                <table v-if="proponente.natureza && proponente.natureza.length > 0"
                       class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Direito</th>
                        <th>Esfera</th>
                        <th>Poder</th>
                        <th>Administra&ccedil;&atilde;o</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ proponente.natureza.direito }}</td>
                        <td>{{ proponente.natureza.esfera }}</td>
                        <td>{{ proponente.natureza.poder }}</td>
                        <td>{{ proponente.natureza.Admins }}</td>
                    </tr>
                    </tbody>
                </table>
                <div v-else>Natureza n&atilde;o informada</div>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Dirigentes</h5>
                <table v-if="proponente.dirigentes && proponente.dirigentes.length > 0"
                       class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th width="20%">CPF</th>
                        <th>Nome</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="dirigente in proponente.dirigentes">
                        <td align="center">{{ dirigente.cnpjcpfdirigente }}</td>
                        <td align="left">{{ dirigente.nomedirigente }}</td>
                    </tr>
                    </tbody>
                </table>
                <div v-else>N&atilde;o existem dirigentes cadastrados!</div>
            </div>
        </div>
    </div>
</script>

<script type="text/x-template" id="dados-usuario">
    <div class="card" v-if="usuario">
        <div class="card-content">
            <h5>Usu&aacute;rio do sistema</h5>
            <div class="row">
                <div class="col s12 l3 m3">
                    <b>CPF</b><br>
                    {{ usuario.cpf}}
                </div>
                <div class="col s12 l3 m3">
                    <b>Nome</b><br>
                    {{ usuario.nome}}
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/x-template" id="texto-simples">
    <div class="card">
        <div class="card-content">
            <div class="row">
                <div class="col s12 l12 m12">
                    <div v-if="texto && texto.length > 1" v-html="texto"></div>
                    <div v-else>Conteúdo n&atilde;o informado</div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/x-template" id="documentos-anexados">
    <div>
        <div class="card">
            <div class="card-content">
                <h5>Documentos da Proposta</h5>
                <table v-if="documentos.proposta" class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Documento</th>
                        <th>Data envio</th>
                        <th>Arquivo</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="documento in documentos.proposta">
                        <td>{{ documento.Descricao }}</td>
                        <td>{{ formatar_data(documento.Data) }}</td>
                        <td>
                            <a :href="documento.url" title="Abrir arquivo">{{documento.NoArquivo}}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div v-else>Nenhum documento da proposta</div>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Documentos do Proponente</h5>
                <table v-if="documentos" class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Documento</th>
                        <th>Data envio</th>
                        <th>Arquivo</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="documento in documentos.proponente">
                        <td>{{ documento.Descricao }}</td>
                        <td>{{ formatar_data(documento.Data) }}</td>
                        <td>
                            <a :href="documento.url" title="Abrir arquivo">{{ documento.NoArquivo }}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div v-else>Nenhum documento do proponente</div>
            </div>
        </div>
    </div>
</script>


<script type="text/x-template" id="local-realizacao-deslocamento">
    <div>
        <div class="card">
            <div class="card-content">
                <h5>Local de Realiza&ccedil;&atilde;o</h5>
                <table v-if="proposta.localizacoes" class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Pais</th>
                        <th>UF</th>
                        <th>Cidade</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="localizacao in proposta.localizacoes">
                        <td>{{ localizacao.pais }}</td>
                        <td>{{ localizacao.uf }}</td>
                        <td>{{ localizacao.cidade }}</td>
                    </tr>
                    </tbody>
                </table>
                <div v-else>Nenhuma localiza&ccedil;&atilde;o</div>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <h5>Deslocamentos</h5>
                <table v-if="proposta.deslocamentos && proposta.deslocamentos.lenght > 1"
                       class="bordered responsive-table">
                    <thead>
                    <tr>
                        <th>Pais de Origem</th>
                        <th>UF de Origem</th>
                        <th>Cidade de Origem</th>
                        <th>Pais de Destino</th>
                        <th>UF de Destino</th>
                        <th>Cidade de Destino</th>
                        <th>Quantidade</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr v-for="deslocamento in proposta.deslocamentos">
                        <td>{{ deslocamento.paisorigem }}</td>
                        <td>{{ deslocamento.uforigem }}</td>
                        <td>{{ deslocamento.municipioorigem }}</td>
                        <td>{{ deslocamento.paisodestino }}</td>
                        <td>{{ deslocamento.ufdestino }}</td>
                        <td>{{ deslocamento.municipiodestino }}</td>
                        <td>{{ deslocamento.Qtde }}</td>
                    </tr>
                    </tbody>
                </table>
                <div v-else>N&atilde;o informado</div>
            </div>
        </div>
    </div>
</script>

<script src="/public/js/vue.js" type="text/javascript"></script>
<script type="text/javascript" src="/public/js/componentes/salic-table-easy.js"></script>
<script src="http://momentjs.com/downloads/moment-with-locales.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js"></script>

<script type="text/javascript">
    Vue.component('salic-proposta', {
        template: '#propostas',
        data: function () {
            return {
                dados: {
                    type: Object,
                    default: function () {
                        return {}
                    }
                }
            }
        },
        props: ['idpreprojeto'],
        mounted: function () {
            this.buscar_dados();
        },
        methods: {
            buscar_dados: function () {
                let vue = this;
                $3.ajax({
                    url: '/proposta/visualizar/identificacao/idPreProjeto/' + vue.idpreprojeto
                }).done(function (response) {
                    vue.dados = response.data;
                });
            }
        }
    });

    Vue.component('salic-proposta-identificacao', {
        template: '#identificacao-da-proposta',
        props: {
            idpreprojeto: null,
            proposta: {
                type: Object,
                default: function () {
                    return {}
                }
            }
        },
        mounted: function () {
        },
        methods: {
            label_sim_ou_nao: function (valor) {
                if (valor == 1)
                    return 'Sim';
                else
                    return 'Não';
            },
            label_mecanismo: function (valor) {
                switch (valor) {
                    case '1':
                        return 'Mecenato';
                        break;
                    default:
                        return 'Inválido';
                        break;
                }
            },
            formatar_data: function (date) {

                date = moment(date).format('DD/MM/YYYY');

                return date;
            },
            label_esfera: function (esfera) {

                let string;

                switch (esfera) {
                    case '1':
                        string = 'Municipal';
                        break;
                    case '2':
                        string = 'Estadual';
                        break;
                    case '3':
                        string = 'Federal';
                        break;
                    default:
                        string = 'Não informada';
                        break;
                }

                return string;
            }
        },
        computed: {
            stDataFixa: function () {
                return this.label_sim_ou_nao(this.proposta.stDataFixa);
            },
            AreaAbrangencia: function () {
                return this.label_sim_ou_nao(this.proposta.AreaAbrangencia);
            },
            tpProrrogacao: function () {
                return this.label_sim_ou_nao(this.proposta.tpProrrogacao);
            },
            Mecanismo: function () {
                return this.label_mecanismo(this.proposta.Mecanismo);
            },
            DtInicioDeExecucao: function () {
                return this.formatar_data(this.proposta.DtInicioDeExecucao);
            },
            DtFinalDeExecucao: function () {
                return this.formatar_data(this.proposta.DtFinalDeExecucao);
            },
            DtAtoTombamento: function () {
                return this.formatar_data(this.proposta.DtAtoTombamento);
            },
            EsferaTombamento: function () {
                return this.label_esfera(this.proposta.EsferaTombamento);
            }
        }
    });


    Vue.component('salic-proposta-historico-avaliacoes', {
        template: '#tabela-simples',
        data: function () {
            return {
                dado: []
            }
        },
        props: ['idpreprojeto'],
        mounted: function () {
            if (typeof this.idpreprojeto != 'undefined') {
                this.fetch(this.idpreprojeto);
            }
        },
        watch: {
            idpreprojeto: function (value) {
                this.fetch(value);
            }
        },
        methods: {
            fetch: function (id) {
                if (id) {
                    let vue = this;
                    $3.ajax({
                        url: '/proposta/visualizar/historico-avaliacoes/idPreProjeto/' + id
                    }).done(function (response) {
                        vue.dado = response.data;
                    });
                }
            },
        }
    });

    Vue.component('salic-agente-proponente', {
        template: '#dados-proponente',
        data: function () {
            return {
                proponente: [],
                identificacao: []
            }
        },
        props: ['idagente'],
        mounted: function () {
            if (typeof this.idagente != 'undefined') {
                this.fetch(this.idagente);
            }
        },
        watch: {
            idagente: function (value) {
                this.fetch(value);
            }
        },
        computed: {
            TipoPessoa: function () {
                return this.label_tipo_pessoa(this.identificacao.tipopessoa);
            }
        },
        methods: {
            fetch: function (id) {
                if (id) {
                    let vue = this;
                    $3.ajax({
                        url: '/proposta/visualizar/dados-proponente/idAgente/' + id
                    }).done(function (response) {
                        vue.proponente = response.data;

                        if (vue.proponente && vue.proponente.identificacao) {
                            vue.identificacao = vue.proponente.identificacao;
                        }
                    });
                }
            },
            label_tipo_pessoa: function (tipo) {
                let string = 'Pessoa Física';

                if (tipo == '1')
                    string = 'Pessoa Jurídica';

                return string;
            },
            label_sim_ou_nao: function (valor) {
                if (valor == 1)
                    return 'Sim';
                else
                    return 'Não';
            }
        }
    });

    Vue.component('salic-agente-usuario', {
        template: '#dados-usuario',
        data: function () {
            return {
                usuario: []
            }
        },
        props: ['idusuario'],
        mounted: function () {
            if (typeof this.idusuario != 'undefined') {
                this.fetch(this.idusuario);
            }
        },
        watch: {
            idusuario: function (value) {
                this.fetch(value);
            }
        },
        methods: {
            fetch: function (id) {
                if (id) {
                    let vue = this;
                    $3.ajax({
                        url: '/proposta/visualizar/dados-usuario/idUsuario/' + id
                    }).done(function (response) {
                        vue.usuario = response.data;
                    });
                }
            }
        }
    });

    Vue.component('salic-proposta-documentos', {
        template: '#documentos-anexados',
        data: function () {
            return {
                documentos: []
            }
        },
        props: ['proposta'],
        mounted: function () {
            if (typeof this.proposta != 'undefined') {
                this.fetch(this.proposta);
            }
        },
        watch: {
            proposta: function (value) {
                this.fetch(value);
            }
        },
        methods: {
            fetch: function (dados) {
                if (typeof dados.default == 'undefined') {

                    let vue = this;
                    $3.ajax({
                        url: '/proposta/visualizar/documentos-anexados/idPreProjeto/' + dados.idPreProjeto + '/idAgente/' + dados.idAgente
                    }).done(function (response) {
                        vue.documentos = response.data;
                    });
                }
            },
            formatar_data: function (date) {

                date = moment(date).format('DD/MM/YYYY');

                return date;
            }
        }
    });

    Vue.component('salic-proposta-local-realizacao-deslocamento', {
        template: '#local-realizacao-deslocamento',
        data: function () {
            return {
                proposta: []
            }
        },
        props: ['idpreprojeto'],
        mounted: function () {
            if (typeof this.idpreprojeto != 'undefined') {
                this.fetch(this.idpreprojeto);
            }
        },
        watch: {
            idpreprojeto: function (value) {
                this.fetch(value);
            }
        },
        methods: {
            fetch: function (id) {
                if (id) {
                    let vue = this;
                    $3.ajax({
                        url: '/proposta/visualizar/local-realizacao-deslocamento/idPreProjeto/' + id
                    }).done(function (response) {
                        vue.proposta = response.data;
                    });
                }
            },
            formatar_data: function (date) {

                date = moment(date).format('DD/MM/YYYY');

                return date;
            }
        }
    });

    Vue.component('salic-proposta-fontes-de-recursos', {
        template: '#tabela-simples',
        data: function () {
            return {
                dado: []
            }
        },
        props: ['idpreprojeto'],
        mounted: function () {
            if (typeof this.idpreprojeto != 'undefined') {
                this.fetch(this.idpreprojeto);
            }
        },
        watch: {
            idpreprojeto: function (value) {
                this.fetch(value);
            }
        },
        methods: {
            fetch: function (id) {
                if (id) {
                    let vue = this;

                    $3.ajax({
                        url: '/proposta/visualizar/fonte-de-recurso/idPreProjeto/' + vue.idpreprojeto
                    }).done(function (response) {
                        vue.dado = response.data;
                    });

                }
            }
        }
    });

    Vue.component('salic-texto-simples', {
        template: '#texto-simples',
        props: ['texto']
    });

    new Vue({
        el: '#container'
    });


    $3(document).ready(function ($) {
        $("#plano-distribuicao").on('click', function () {
            let idRetorno = 'plano-distribuicao';
            jqAjaxLink('<?php echo $this->url(['module' => 'proposta', 'controller' => 'visualizar-plano-distribuicao', 'action' => 'visualizar', 'idPreProjeto' => $this->idPreProjeto]); ?>', '', 'html-plano-distribuicao');
        });

        $("#planilha-orcamentaria").on('click', function () {
            jqAjaxLink('<?php echo $this->Url(array('module' => 'default', 'controller' => 'index', 'action' => 'montar-planilha-orcamentaria')) ?>?idPronac=<?= $this->idPreProjeto; ?>&tipoPlanilha=0', '', 'planilhaOrcamentariaMontada');
        });

    });
</script>
