<div id="container" class="container-fluid">
    <salic-proposta idpreprojeto="<?= $this->idPreProjeto; ?>"></salic-proposta>
</div>

<script type="text/x-template" id="texto-simples">
    <div class="texto-simples">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col s12 l12 m12">
                        <div v-if="texto && texto.length > 1" v-html="texto"></div>
                        <div v-else>Conteúdo n&atilde;o informado</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>


<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="http://momentjs.com/downloads/moment-with-locales.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js"></script>

<script type="text/javascript" src="/public/js/componentes/salic-table-easy.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-identificacao.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-documentos.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-fontes-de-recursos.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-historico-avaliacoes.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-local-realizacao-deslocamento.vue.js"></script>
<script type="text/javascript" src="/public/scripts/agente/salic-agente-proponente.vue.js"></script>
<script type="text/javascript" src="/public/scripts/agente/salic-agente-usuario.vue.js"></script>

<script type="text/javascript">

    Vue.component('salic-texto-simples', {
        template: '#texto-simples',
        props: ['texto']
    });

    new Vue({
        el: '#container'
    });


    $3(document).ready(function ($) {
        $("#plano-distribuicao").on('click', function () {
            let idRetorno = 'plano-distribuicao';
            jqAjaxLink('<?php echo $this->url(['module' => 'proposta', 'controller' => 'visualizar-plano-distribuicao', 'action' => 'visualizar', 'idPreProjeto' => $this->idPreProjeto]); ?>', '', 'html-plano-distribuicao');
        });

        $("#planilha-orcamentaria").on('click', function () {
            jqAjaxLink('<?php echo $this->Url(array('module' => 'default', 'controller' => 'index', 'action' => 'montar-planilha-orcamentaria')) ?>?idPronac=<?= $this->idPreProjeto; ?>&tipoPlanilha=0', '', 'planilhaOrcamentariaMontada');
        });

    });
</script>
