<?php
    $hrefAnalisedeconteudo = $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'analisedeconteudo'));
    $hrefAlteraritemsolicitado = $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'alteraritemsolicitado'));

    /* INICIO DA GUIA DE LINKS */
    $controller = 'analisarprojetoparecer';
    $links = array();
    $links[] = array('Projetos/Produtos para An&aacute;lise' => array('module' => 'parecer' , 'controller' => 'analise-inicial', 'action' => 'index'));
    $links[] = array('An&aacute;lise do Produto' => array());

    /* FIM DA GUIA DE LINKS */
?>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.css" />

<div class="container-fluid">
    <!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
    <div class="row" >
        <div class="col s12">
            <div id="breadcrumb">
                <ul>
                    <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">In&iacute;cio</a></li>
                    <li class="second">An&aacute;lise T&eacute;cnica Inicial</li>
                    <li class="second"><a href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analise-inicial', 'action' => 'index'), '', true); ?>" title="Ir para P&aacute;gina Inicial">Projetos/Produtos para An&aacute;lise</a></li>
                    <li class="last">An&aacute;lise do Produtos</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row" >
        <div class="col s12">
            <h3 class="left">An&aacute;lise do Produto </h3>
            <a class="btn right" href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a>
        </div>
    </div>
    <div id="dialog-valor" class="sumir" title="Valor Inv&aacute;lido">
        <div class="msgERROR">
            <div>Valor de remanejamento maior que o permitido! M&aacute;ximo : <span id="valorpossivelApresentacao"></span></div>
        </div>
    </div>
    <div class="row" >
        <div class="col s12">
            <h4>An&aacute;lise de Conte&uacute;do do Projeto Nr: <?php echo $this->projeto->PRONAC; ?> - <?php echo $this->projeto->NomeProjeto; ?></h4>
            <h5>Produto
                <?php if ($this->projeto->stPrincipal): ?>
                    Principal
                <?php else:  ?>
                    Secundario
                <?php endif;  ?>
               : <?php echo $this->projeto->dsProduto; ?>
            </h5>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
          <ul class="tabs">
            <li class="tab col s3"><a class="active" href="#test1">An&aacute;lise de conte&uacute;do</a></li>
            <li class="tab col s3"><a href="#test2">An&aacute;lise de custos</a></li>
                <li
                    class="tab col s3
                            <?php if(!(($this->stPrincipal == 1) && ($this->grupoAtivo == Autenticacao_Model_Grupos::PARECERISTA))): ?>
                                disabled text-gray grey lighten-2
                            <?php endif; ?>
                ">
                    <a href="#test3">Dados dos Produtos Secund&aacute;rios</a></li>
                <li class="tab col s3
                            <?php if(!(($this->stPrincipal == 1) && ($this->produtosSecundariosEmAnalise == 0))): ?>
                                disabled grey lighten-2
                            <?php endif; ?>
                ">
                    <a href="#test4">Consolida&ccedil;&atilde;o do Parecer T&eacute;cnico</a>
                </li>
          </ul>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <div id="test1" class="col s12">
                <?php echo $this->partial('produto/analise-conteudo.phtml', 'parecer', $this); ?>
            </div>
            <div id="test2" class="col s12">
                <?php echo $this->partial('produto/analise-custo.phtml', 'parecer', $this); ?>
            </div>
            <?php if(($this->stPrincipal == 1) && ($this->grupoAtivo == Autenticacao_Model_Grupos::PARECERISTA)): ?>
                <div id="test3" class="col s12">
                    <?php echo $this->partial('produto/secundarios.phtml', 'parecer', $this); ?>
                </div>
            <?php endif; ?>
            <?php if(($this->stPrincipal == 1) && ($this->produtosSecundariosEmAnalise == 0)): ?>
                <div id="test4" class="col s12">
                    <?php echo $this->partial('produto/consolidacao.phtml', 'parecer', $this); ?>
               </div>
            <?php endif; ?>
        </div>
        <!-- MODAL -->
        <div id="alteraritemsolicitado" link="<?php echo $hrefAlteraritemsolicitado; ?>" style="display: none;"></div>
        <div id="confirmacao" style="display: none;"></div>
        <!-- FIM MODAL -->
    </div>
</div>
<!-- ========== FIM CONTE&UACUTE;DO ========== -->

<div id="confirma" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>

<input type="hidden" name="grupoAtivo" id="grupoAtivo" value="<?php echo $this->grupoAtivo; ?>" />
<input type="hidden" name="somenteLeitura" id="somenteLeitura" value="<?php echo $this->somenteLeitura ? 1 : 0; ?>" />
<input type="hidden" name="IN2017" id="IN2017" value="<?php echo ($this->IN2017 == 1)? 1 : 0; ?>" />
<input type="hidden" name="stPrincipal" id="stPrincipal" value="<?php echo ($this->stPrincipal == 1) ? 1 : 0; ?>" />
<input type="hidden" name="produtosSecundariosEmAnalise" id="produtosSecundariosEmAnalise" value="<?php echo ($this->produtosSecundariosEmAnalise > 0 ) ? 1 : 0; ?>" />
<input type="hidden" name="valorpossivelApresentacao" id="valorpossivelApresentacao" value="<?php echo $this->formatarReal($this->valorpossivel);?>" />
<input type="hidden" name="IdPRONAC" id="IdPRONAC" value="<?php echo $this->projeto->IdPRONAC; ?>" />
<input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>" />
<input type="hidden" name="vlSolicitado" id="vlSolicitado" value="<?php echo $this->vlSolicitado;?>" />
<input type="hidden" name="idProduto" id="idProduto" value="<?php echo $this->projeto->idProduto; ?>" />

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery/plugins/editorRico.js"></script>

<script type="text/javascript" src="/public/scripts/default/analisarprojetoparecer/produto.js"></script>
<script type="text/javascript">APPescolherArt_18(); APPescolherArt_26(); APPescolherLei_8313(); APPescolherArtigo3();</script>
