<?= $this->partial("analise-inicial/partials/menu-suspenso.phtml", $this); ?>

<div>analisar projeto e produto atual</div>

<div id="analisar-conteudo" class="modal bottom-sheet" style="min-height: 700px">
    <div class="modal-content">
        <h4>Modal Header</h4>
        <p>texto analisar conteudo</p>
    </div>
</div>

<div id="analisar-custos" class="modal bottom-sheet" style="min-height: 700px">
    <div class="modal-content">
        <h4>Modal Header</h4>
        <p>Analise de custos</p>
    </div>
</div>

<div id="consolidar-parecer-tecnico" class="modal bottom-sheet" style="min-height: 700px">
    <div class="modal-content">
        <h4>Modal Header</h4>
        <p>Consolidar parecer</p>
    </div>
</div>

<script>

    $3(document).ready(function($){
        // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
        $('.modal').modal({
            dismissible: true, // Modal can be dismissed by clicking outside of the modal
            opacity: .6, // Opacity of modal background
            inDuration: 100, // Transition in duration
            outDuration: 100, // Transition out duration
            startingTop: '4%', // Starting top style attribute
            endingTop: '10%', // Ending top style attribute
            ready: function(modal, trigger) { // Callback for Modal open. Modal and trigger parameters available.
                console.log("Ready");
                console.log(modal, trigger);
            },
            complete: function(modal) {

                Materialize.toast("Salvando conte&uacute;do...", 4000);
                console.log(modal);
            } // Callback for Modal close
        });
    });

</script>