<?= $this->partial("analise-inicial/partials/menu-suspenso.phtml", $this); ?>

<div id="container" class="container-fluid">

    <salic-proposta idpreprojeto="<?= $this->idPreProjeto; ?>"></salic-proposta>

    <div id="analisar-conteudo" class="modal bottom-sheet">
        <div class="modal-content">
            <h4>Analisar conte&uacute;do</h4>
            <?php echo $this->partial('analise-inicial/partials/analisar-conteudo.phtml', 'parecer', $this); ?>
        </div>
    </div>

    <div id="analisar-custos" class="modal bottom-sheet">
        <div class="modal-content">
            <h4>An&aacute;lise de Custos</h4>
            <div id="planilha-analise-de-custos"></div>
            <?php echo $this->partial('analise-inicial/partials/analisar-custo.phtml', 'parecer', $this->custos); ?>
        </div>
    </div>

    <div id="consolidar-parecer-tecnico" class="modal bottom-sheet">
        <div class="modal-content">
            <h4>Consolidar parecer t&eacute;cnico</h4>
            <?php if (($this->stPrincipal == 1) && ($this->grupoAtivo == Autenticacao_Model_Grupos::PARECERISTA)): ?>
                <?php echo $this->partial('analise-inicial/partials/secundarios.phtml', 'parecer', $this); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<div id="confirma" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>

<input type="hidden" name="grupoAtivo" id="grupoAtivo" value="<?php echo $this->grupoAtivo; ?>"/>

<input type="hidden" name="vlSolicitado" id="vlSolicitado" value="<?php echo $this->vlSolicitado; ?>"/>
<input type="hidden" name="produtosSecundariosEmAnalise" id="produtosSecundariosEmAnalise"
       value="<?php echo ($this->produtosSecundariosEmAnalise > 0) ? 1 : 0; ?>"/>
<input type="hidden" name="valorpossivelApresentacao" id="valorpossivelApresentacao"
       value="<?php echo $this->formatarReal($this->valorpossivel); ?>"/>
<input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>"/>

<!-- analise de conteudo -->
<input type="hidden" name="stPrincipal" id="stPrincipal" value="<?php echo ($this->stPrincipal == 1) ? 1 : 0; ?>"/>
<input type="hidden" name="somenteLeitura" id="somenteLeitura" value="<?php echo $this->somenteLeitura ? 1 : 0; ?>"/>
<input type="hidden" name="IdPRONAC" id="IdPRONAC" value="<?php echo $this->projeto->IdPRONAC; ?>"/>
<input type="hidden" name="idProduto" id="idProduto" value="<?php echo $this->projeto->idProduto; ?>"/>
<input type="hidden" name="IN2017" id="IN2017" value="<?php echo ($this->IN2017 == 1) ? 1 : 0; ?>"/>


<!-- analise de custo -->
<div id="alteraritemsolicitado" link="<?= $hrefAlteraritemsolicitado; ?>" style="display: none;"></div>
<div id="confirmacao" style="display: none;"></div>

<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="http://momentjs.com/downloads/moment-with-locales.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js"></script>

<script type="text/javascript" src="/public/js/componentes/salic-table-easy.js"></script>
<script type="text/javascript" src="/public/js/componentes/salic-texto-simples.vue.js"></script>

<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-identificacao.vue.js"></script>
<script type="text/javascript" src="/public/scripts/proposta/visualizar/salic-proposta-documentos.vue.js"></script>
<script type="text/javascript"
        src="/public/scripts/proposta/visualizar/salic-proposta-fontes-de-recursos.vue.js"></script>
<script type="text/javascript"
        src="/public/scripts/proposta/visualizar/salic-proposta-historico-avaliacoes.vue.js"></script>
<script type="text/javascript"
        src="/public/scripts/proposta/visualizar/salic-proposta-local-realizacao-deslocamento.vue.js"></script>
<script type="text/javascript" src="/public/scripts/agente/visualizar/salic-agente-proponente.vue.js"></script>
<script type="text/javascript" src="/public/scripts/autenticacao/index/salic-autenticacao-usuario.vue.js"></script>


<script type="text/javascript" src="/public/scripts/parecer/analisarprojetoparecer/produto.js"></script>
<script type="text/javascript">APPescolherArt_18();
    APPescolherArt_26();
    APPescolherLei_8313();
    APPescolherArtigo3();</script>

<script type="text/javascript">

    new Vue({
        el: '#container'
    });


    $3(document).ready(function ($) {

        var dadosFormulario = '';
        var elmBody = $('body');

        var dados = {
            idPronac: $('#IdPRONAC').val(),
            idProduto: $('#idProduto').val(),
            stPrincipal: $('#stPrincipal').val()
        };

        jqAjaxLink('/parecer/analise-inicial/analisar-custos', dados, 'planilha-analise-de-custos');

        elmBody.on('submit', 'form', function () {

            if (typeof tinyMCE == 'object') {
                tinyMCE.triggerSave();
            }

            dadosFormulario = $(this).serialize();

            $(this).ajaxFormSubmit();
            return false;
        });

        $('.modal').each(function () {
            $(this).css('min-height', $(window).height() - 94);
        }).modal({
            dismissible: true,
            opacity: .6,
            inDuration: 50,
            outDuration: 50,
            startingTop: '4%',
            endingTop: '10%',
            ready: function (modal, trigger) {

                if (typeof tinyMCE == 'object') {
                    tinyMCE.triggerSave();
                }

                dadosFormulario = $(modal).find('form').serialize();
            },
            complete: function (modal) {

                if (typeof tinyMCE == 'object') {
                    tinyMCE.triggerSave();
                }

                if (dadosFormulario != $(modal).find('form').serialize()) {
                    Materialize.toast("Salvando altera&ccedil;&otilde;es...", 4000);
                    $(modal).find('form').submit();
                }
            }
        });

        elmBody.on('click', '#plano-distribuicao', function () {
            let idRetorno = 'plano-distribuicao';
            jqAjaxLink('<?php echo $this->url(['module' => 'proposta', 'controller' => 'visualizar-plano-distribuicao', 'action' => 'visualizar', 'idPreProjeto' => $this->idPreProjeto]); ?>', '', 'html-plano-distribuicao');
        });

        elmBody.on('click', '#planilha-orcamentaria', function () {
            jqAjaxLink('<?php echo $this->Url(array('module' => 'default', 'controller' => 'index', 'action' => 'montar-planilha-orcamentaria')) ?>?idPronac=<?= $this->idPreProjeto; ?>&tipoPlanilha=0', '', 'planilhaOrcamentariaMontada');
        });
    });

</script>

