<?= $this->partial("analise-inicial/partials/menu-suspenso.phtml", $this); ?>

<div id="container" class="container-fluid">

    <div id="dialog-valor" class="sumir" title="Valor Inv&aacute;lido">
        <div class="msgERROR">
            <div>
                Valor de remanejamento maior que o permitido! M&aacute;ximo :
                <span id="valorpossivelApresentacao"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <div id="breadcrumb">
                <ul>
                    <li class="first"><a
                            href="<?php echo $this->url(
                                array(
                                    'controller' => 'principal',
                                    'action' => ''),
                                '', true); ?>"
                            title="Ir para P&aacute;gina Inicial"
                        >
                            In&iacute;cio
                        </a>
                    </li>
                    <li class="second">An&aacute;lise T&eacute;cnica Inicial</li>
                    <li class="second"><a
                            href="<?php echo $this->url(
                                array(
                                    'module' => 'parecer',
                                    'controller' => 'analise-inicial',
                                    'action' => 'index'
                                ), '', true); ?>"
                            title="Ir para P&aacute;gina Inicial"
                        >
                            Projetos/Produtos para An&aacute;lise
                        </a>
                    </li>
                    <li class="last">An&aacute;lise do Produtos</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <h4 class="left">An&aacute;lise do Produto </h4>
            <a class="btn right"
               href="<?php echo $this->url(
                   array(
                       'module' => 'parecer',
                       'controller' => 'analise-inicial',
                       'action' => 'index'),
                   '', true); ?>#produto_<?= $this->projeto->idProduto ?>"
               title="P&aacute;gina Anterior"
            >
                Voltar
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <p><b>Projeto: </b><?= $this->projeto->PRONAC; ?> - <?= $this->projeto->NomeProjeto; ?></p>
            <p>
                <b>Produto <?= ($this->projeto->stPrincipal) ? 'Principal' : 'Secund&aacute;rio'; ?>: </b>
                <?php echo $this->projeto->dsProduto; ?>
            </p>
            <p><b>Situa&ccedil;&atilde;o: </b><?= $this->situacao; ?></p>
        </div>
    </div>
    
    <div class="row">
        <div class="col s12 green">
            <ul class="tabs tabs-transparent">
                <li class="tab"><a href="#tab-analise-projeto">Projeto</a></li>
                <li class="tab"><a href="#modal-analisar-conteudo" target="_top">Analisar conte&uacute;do</a></li>
                <li class="tab"><a href="#tab-analise-custo" class="bt-analisar-custos">Analisar custos</a></li>

                <?php if (($this->projeto->stPrincipal == 1) && ($this->codGrupo == Autenticacao_Model_Grupos::PARECERISTA)): ?>
                    <?php if ($this->existeProdutoSecundario) : ?>
                        <li class="tab">
                            <a href="#tab-produtos-secundarios">Produtos Secund&aacute;rios</a>
                        </li>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($this->projeto->stPrincipal == 1) : ?>
                    <li class="tab">
                        <a
                            target="_top"
                            class="modal-trigger <?= ($this->produtosSecundariosEmAnalise == 0) ? '' : 'disabled'; ?>"
                            href="#modal-consolidar-parecer-tecnico">
                            Consolidar Parecer T&eacute;cnico
                        </a>
                    </li>
                <?php endif; ?>
                <li class="tab"><a href="#tab-finalizar-parecer-tecnico">Finalizar</a></li>
            </ul>
        </div>

        <div id="tab-analise-projeto" class="col s12">
            <div id="container-vue">
                <salic-proposta idpreprojeto="<?= $this->projeto->idProjeto; ?>"></salic-proposta>

                <div class="center-align">
                    <a
                        class="btn blue tooltipped waves-effect waves-light modal-trigger"
                        data-tooltip="An&aacute;lise de Conte&uacute;do"
                        href="#modal-analisar-conteudo">
                        <i class="material-icons left">playlist_add_check</i>
                        Analisar conte&uacute;do
                    </a>
                </div>
            </div>
        </div>

        <div id="tab-analise-custo" class="col s12">
            <div id="planilha-analise-de-custos"></div>
        </div>

        <?php if ($this->projeto->stPrincipal == 1): ?>
            <?php if ($this->existeProdutoSecundario) : ?>
                <div id="tab-produtos-secundarios" class="col s12">
                    <?php echo $this->partial('analise-inicial/partials/produtos-secundarios.phtml', 'parecer', $this); ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <div id="tab-finalizar-parecer-tecnico" class="col s12">
            <div id="finalizar-parecer-tecnico"></div>
        </div>
    </div>

    <div id="modal-analisar-conteudo" class="modal bottom-sheet">
        <div class="modal-contents">
            <?= $this->partial('analise-inicial/partials/analisar-conteudo.phtml', 'parecer', $this); ?>
        </div>
    </div>

    <div id="modal-consolidar-parecer-tecnico" class="modal bottom-sheet">
        <div class="modal-contents">
            <?php if ($this->projeto->stPrincipal == 1): ?>
                <?= $this->partial('analise-inicial/partials/consolidar-parecer.phtml', 'parecer', $this); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<div id="confirma" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>
<input type="hidden" name="grupoAtivo" id="grupoAtivo" value="<?= $this->codGrupo; ?>"/>
<input type="hidden" name="vlSolicitado" id="vlSolicitado" value="<?= $this->vlSolicitado; ?>"/>
<input type="hidden" name="produtosSecundariosEmAnalise" id="produtosSecundariosEmAnalise"
       value="<?= ($this->produtosSecundariosEmAnalise > 0) ? 1 : 0; ?>"/>
<input type="hidden" name="valorpossivelApresentacao" id="valorpossivelApresentacao"
       value="<?= $this->formatarReal($this->valorpossivel); ?>"/>
<input type="hidden" name="baseUrl" id="baseUrl" value="<?= $this->baseUrl(); ?>"/>
<input type="hidden" name="stPrincipal" id="stPrincipal" value="<?= ($this->projeto->stPrincipal == 1) ? 1 : 0; ?>"/>
<input type="hidden" name="somenteLeitura" id="somenteLeitura" value="<?= $this->somenteLeitura ? 1 : 0; ?>"/>
<input type="hidden" name="IdPRONAC" id="IdPRONAC" value="<?= $this->projeto->IdPRONAC; ?>"/>
<input type="hidden" name="idProduto" id="idProduto" value="<?= $this->projeto->idProduto; ?>"/>
<input type="hidden" name="IN2017" id="IN2017" value="<?= ($this->IN2017 == 1) ? 1 : 0; ?>"/>

<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="http://momentjs.com/downloads/moment-with-locales.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>

<script src="/public/js/componentes/salic-table-easy.js" type="text/javascript"></script>
<script src="/public/js/componentes/salic-texto-simples.vue.js" type="text/javascript"></script>

<script src="/public/scripts/proposta/visualizar/salic-proposta.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-identificacao.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-documentos.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-fontes-de-recursos.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-historico-avaliacoes.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-local-realizacao-deslocamento.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/agente/visualizar/salic-agente-proponente.vue.js" type="text/javascript"></script>
<script src="/public/scripts/autenticacao/index/salic-autenticacao-usuario.vue.js" type="text/javascript"></script>

<script type="text/javascript" src="/public/scripts/parecer/analise-inicial/analisar-conteudo.js"></script>
<script type="text/javascript" src="/public/scripts/parecer/analise-inicial/analisar-custos.js"></script>
<script type="text/javascript" src="/public/scripts/parecer/analise-inicial/consolidar-parecer.js"></script>

<?php if (!$this->IN2017) : ?>
    <script type="text/javascript">
        APPescolherArt_18();
        APPescolherArt_26();
        APPescolherLei_8313();
        APPescolherArtigo3();
    </script>
<?php endif; ?>

<script type="text/javascript">

    new Vue({
        el: '#container-vue'
    });

    $3(document).ready(function ($) {

        var dadosFormulario = '';
        var elmBody = $('body');

        elmBody.on('submit', 'form', function () {

            if (typeof tinyMCE == 'object') {
                tinyMCE.triggerSave();
            }

            dadosFormulario = $(this).serialize();

            $(this).ajaxFormSubmit();
            return false;
        });

        $('.modal').each(function () {
            $(this).css('min-height', $(window).height());
        }).modal({
            dismissible: true,
            opacity: .6,
            inDuration: 50,
            outDuration: 50,
            startingTop: '4%',
            endingTop: '10%',
            ready: function (modal, trigger) {

                if (typeof tinyMCE == 'object') {
                    tinyMCE.triggerSave();
                }

                dadosFormulario = $(modal).find('form').serialize();
            },
            complete: function (modal) {

                if (typeof tinyMCE == 'object') {
                    tinyMCE.triggerSave();
                }

                if (dadosFormulario != $(modal).find('form').serialize()) {
                    Materialize.toast("Salvando altera&ccedil;&otilde;es...", 4000);
                    $(modal).find('form').submit();
                }
            }
        });

        elmBody.on('click', '#plano-distribuicao', function () {
            let idRetorno = 'plano-distribuicao';
            jqAjaxLink('<?php echo $this->url(
                [
                    'module' => 'proposta',
                    'controller' => 'visualizar-plano-distribuicao',
                    'action' => 'visualizar',
                    'idPreProjeto' => $this->projeto->idProjeto
                ]); ?>', '', 'html-plano-distribuicao');
        });

        elmBody.on('click', '#planilha-orcamentaria', function () {
            jqAjaxLink('<?php echo $this->url(
                [
                    'module' => 'default',
                    'controller' => 'index',
                    'action' => 'montar-planilha-orcamentaria'
                ]
            ) ?>?idPronac=<?= $this->projeto->idProjeto; ?>&tipoPlanilha=0', '', 'planilhaOrcamentariaMontada');
        });

        let dados = {
            idPronac: $('#IdPRONAC').val(),
            idProduto: $('#idProduto').val(),
            stPrincipal: $('#stPrincipal').val()
        };

        elmBody.on('click', "a[href='#tab-analise-custo']", function () {
            jqAjaxLink('/parecer/analise-inicial/analisar-custos', dados, 'planilha-analise-de-custos');
        });

        elmBody.on('click', "a[href='#tab-finalizar-parecer-tecnico']", function () {
            jqAjaxLink('/parecer/analise-inicial/obter-finalizacao-parecer-modal', dados, 'finalizar-parecer-tecnico');
        });

//        $('.tabs').on('click', 'a', function (e) {
//            e.preventDefault();
//
//            let offset = $(this).offset();
//
//            $('html,body').animate({
//                scrollTop: offset.top - 70
//            }, 700);
//        });

    });

</script>

