<?= $this->partial("analise-inicial/partials/menu-suspenso.phtml", $this); ?>

<div id="container" class="container-fluid">

    <div id="dialog-valor" class="sumir" title="Valor Inv&aacute;lido">
        <div class="msgERROR">
            <div>Valor de remanejamento maior que o permitido! M&aacute;ximo : <span id="valorpossivelApresentacao"></span></div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <div id="breadcrumb">
                <ul>
                    <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">In&iacute;cio</a></li>
                    <li class="second">An&aacute;lise T&eacute;cnica Inicial</li>
                    <li class="second"><a href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analise-inicial', 'action' => 'index'), '', true); ?>" title="Ir para P&aacute;gina Inicial">Projetos/Produtos para An&aacute;lise</a></li>
                    <li class="last">An&aacute;lise do Produtos</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row" >
        <div class="col s12">
            <h3 class="left">An&aacute;lise do Produto </h3>
            <a class="btn right" href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analise-inicial', 'action' => 'index'), '', true); ?>#produto_<?= $this->projeto->idProduto?>" title="P&aacute;gina Anterior">Voltar</a>
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <h4>Projeto: <?= $this->projeto->PRONAC; ?> - <?= $this->projeto->NomeProjeto; ?></h4>
            <h5>Produto <?= ($this->projeto->stPrincipal) ? 'Principal' : 'Secund&aacute;rio'; ?>
                : <?php echo $this->projeto->dsProduto; ?>
            </h5>
        </div>
    </div>

    <div class="row">

        <div class="col s12">
            <ul class="tabs tabs-fixed-width">
                <li class="tab">
                    <a href="#tab_analise_projeto">Projeto</a>
                </li>
                <li class="tab">
                    <a href="#tab_analise_custo">Analisar custos do Produto</a>
                </li>
                <?php if(($this->stPrincipal == 1) && ($this->grupoAtivo == Autenticacao_Model_Grupos::PARECERISTA)): ?>
                    <li class="tab">
                        <a href="#tab_produtos_secundarios">Dados dos Produtos Secund&aacute;rios</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>

        <div id="tab_analise_projeto" class="col s12">
            <div id="container-vue">
                <salic-proposta idpreprojeto="<?= $this->idPreProjeto; ?>"></salic-proposta>
            </div>
        </div>

        <div id="tab_analise_custo" class="col s12">
            <div id="planilha-analise-de-custos"></div>
        </div>
        <?php if(($this->stPrincipal == 1) && ($this->grupoAtivo == Autenticacao_Model_Grupos::PARECERISTA)): ?>
            <div id="tab_produtos_secundarios" class="col s12">
                <?php echo $this->partial('produto/secundarios.phtml', 'parecer', $this); ?>
            </div>
        <?php endif; ?>
    </div>

    <div id="analisar-conteudo" class="modal bottom-sheet">
        <div class="modal-content">
            <h4>Analisar conte&uacute;do</h4>
            <?php echo $this->partial('analise-inicial/partials/analisar-conteudo.phtml', 'parecer', $this); ?>
        </div>
    </div>

    <div id="consolidar-parecer-tecnico" class="modal bottom-sheet">
        <div class="modal-content">
            <h4>Consolidar parecer t&eacute;cnico</h4>
            <?php if (($this->stPrincipal == 1) && ($this->grupoAtivo == Autenticacao_Model_Grupos::PARECERISTA)): ?>
                <?php echo $this->partial('analise-inicial/partials/secundarios.phtml', 'parecer', $this); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<div id="confirma" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>

<input type="hidden" name="grupoAtivo" id="grupoAtivo" value="<?php echo $this->grupoAtivo; ?>"/>

<input type="hidden" name="vlSolicitado" id="vlSolicitado" value="<?php echo $this->vlSolicitado; ?>"/>
<input type="hidden" name="produtosSecundariosEmAnalise" id="produtosSecundariosEmAnalise"
       value="<?php echo ($this->produtosSecundariosEmAnalise > 0) ? 1 : 0; ?>"/>
<input type="hidden" name="valorpossivelApresentacao" id="valorpossivelApresentacao"
       value="<?php echo $this->formatarReal($this->valorpossivel); ?>"/>
<input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>"/>

<!-- analise de conteudo -->
<input type="hidden" name="stPrincipal" id="stPrincipal" value="<?php echo ($this->stPrincipal == 1) ? 1 : 0; ?>"/>
<input type="hidden" name="somenteLeitura" id="somenteLeitura" value="<?php echo $this->somenteLeitura ? 1 : 0; ?>"/>
<input type="hidden" name="IdPRONAC" id="IdPRONAC" value="<?php echo $this->projeto->IdPRONAC; ?>"/>
<input type="hidden" name="idProduto" id="idProduto" value="<?php echo $this->projeto->idProduto; ?>"/>
<input type="hidden" name="IN2017" id="IN2017" value="<?php echo ($this->IN2017 == 1) ? 1 : 0; ?>"/>

<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="http://momentjs.com/downloads/moment-with-locales.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>

<script src="/public/js/componentes/salic-table-easy.js" type="text/javascript"></script>
<script src="/public/js/componentes/salic-texto-simples.vue.js" type="text/javascript"></script>

<script src="/public/scripts/proposta/visualizar/salic-proposta.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-identificacao.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-documentos.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-fontes-de-recursos.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-historico-avaliacoes.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-local-realizacao-deslocamento.vue.js" type="text/javascript"></script>
<script src="/public/scripts/agente/visualizar/salic-agente-proponente.vue.js" type="text/javascript"></script>
<script src="/public/scripts/autenticacao/index/salic-autenticacao-usuario.vue.js" type="text/javascript"></script>

<!--<script type="text/javascript" src="/public/scripts/parecer/analisarprojetoparecer/produto.js"></script>-->
<script type="text/javascript" src="/public/scripts/parecer/analise-inicial/analisar-conteudo.js"></script>
<script type="text/javascript" src="/public/scripts/parecer/analise-inicial/analisar-custos.js"></script>
<script type="text/javascript" src="/public/scripts/parecer/analise-inicial/consolidar-parecer.js"></script>

<?php if(!$this->IN2017) : ?>
    <script type="text/javascript">
        APPescolherArt_18();
        APPescolherArt_26();
        APPescolherLei_8313();
        APPescolherArtigo3();
    </script>
<?php endif; ?>

<script type="text/javascript">

    new Vue({
        el: '#container-vue'
    });

    $3(document).ready(function ($) {

        var dadosFormulario = '';
        var elmBody = $('body');

        elmBody.on('submit', 'form', function () {

            if (typeof tinyMCE == 'object') {
                tinyMCE.triggerSave();
            }

            dadosFormulario = $(this).serialize();

            $(this).ajaxFormSubmit();
            return false;
        });

        $('.modal').each(function () {
            $(this).css('min-height', $(window).height() - 94);
        }).modal({
            dismissible: true,
            opacity: .6,
            inDuration: 50,
            outDuration: 50,
            startingTop: '4%',
            endingTop: '10%',
            ready: function (modal, trigger) {

                if (typeof tinyMCE == 'object') {
                    tinyMCE.triggerSave();
                }

                dadosFormulario = $(modal).find('form').serialize();
            },
            complete: function (modal) {

                if (typeof tinyMCE == 'object') {
                    tinyMCE.triggerSave();
                }

                if (dadosFormulario != $(modal).find('form').serialize()) {
                    Materialize.toast("Salvando altera&ccedil;&otilde;es...", 4000);
                    $(modal).find('form').submit();
                }
            }
        });

        elmBody.on('click', '#plano-distribuicao', function () {
            let idRetorno = 'plano-distribuicao';
            jqAjaxLink('<?php echo $this->url(['module' => 'proposta', 'controller' => 'visualizar-plano-distribuicao', 'action' => 'visualizar', 'idPreProjeto' => $this->idPreProjeto]); ?>', '', 'html-plano-distribuicao');
        });

        elmBody.on('click', '#planilha-orcamentaria', function () {
            jqAjaxLink('<?php echo $this->Url(array('module' => 'default', 'controller' => 'index', 'action' => 'montar-planilha-orcamentaria')) ?>?idPronac=<?= $this->idPreProjeto; ?>&tipoPlanilha=0', '', 'planilhaOrcamentariaMontada');
        });

        var dados = {
            idPronac: $('#IdPRONAC').val(),
            idProduto: $('#idProduto').val(),
            stPrincipal: $('#stPrincipal').val()
        };

        jqAjaxLink('/parecer/analise-inicial/analisar-custos', dados, 'planilha-analise-de-custos');

    });

</script>

