<?php
$isProdutosSecundariosAnalisados = $this->IsProdutosSecundariosAnalisados($this->projeto->IdPRONAC);
$isProdutosPendentesParecer = $this->IsProdutosPendentesParecer($this->projeto->IdPRONAC, $this->projeto->idProduto);
$isProjetoEnquadrado = $this->IsProjetoEnquadrado($this->projeto->IdPRONAC);
$isProjetoComParecer = $this->IsProjetoComParecer($this->projeto->IdPRONAC);
?>
<div class="padding20 center-align">
    <div class="botoes">
        <?php if (
            ($isProdutosSecundariosAnalisados) &&
            ($this->projeto->stPrincipal == 1) &&
            (!$isProdutosPendentesParecer) &&
            ($isProjetoEnquadrado) &&
            ($isProjetoComParecer) &&
            ($this->quantidadeDiligencias == 0)
        ) : ?>
            <?php if ($this->IN2017): ?>

                <?php $isProjetoDisponivelParaAssinatura = $this->IsProjetoDisponivelParaAssinatura(
                    $this->projeto->IdPRONAC,
                    $this->idTipoDoAtoAdministrativo
                ); ?>

                <?php if ($isProjetoDisponivelParaAssinatura): ?>

                    <?php $idDocumentoAssinatura = $this->GetIdDocumentoAssinatura(
                        $this->projeto->IdPRONAC,
                        $this->idTipoDoAtoAdministrativo
                    ); ?>

                    <a class="btn waves-effect waves-light cyan tooltipped small"
                       href="<?php echo $this->url(
                               array(
                                   'module' => 'assinatura',
                                   'controller' => 'index',
                                   'action' => 'visualizar-projeto')
                           ) . "?idDocumentoAssinatura=" . $idDocumentoAssinatura; ?>&origin=parecer/analise-inicial"
                       data-tooltip="Visualizar documento"
                    >
                        <i class="material-icons white-text">remove_red_eye</i>
                    </a>

                    <?php $isProjetoJaAssinado = $this->IsProjetoJaAssinado(
                        $this->projeto->IdPRONAC,
                        $this->idTipoDoAtoAdministrativo,
                        $this->idGrupoAtivo);
                    ?>

                    <?php if ($isProjetoJaAssinado) : ?>

                        <?php
                        $parametrosAssinatura = "?idPronac="
                            . $this->projeto->IdPRONAC
                            . "&idProduto=" . $this->projeto->idProduto
                            . "&situacao=" . $this->projeto->situacao
                            . "&idD=" . $this->projeto->idDistribuirParecer
                            . "&concluir=1";
                        ?>

                        <a class="btn waves-effect waves-light tooltipped small btn cyan"
                           href="#modalConfirmacao"
                           data-redirect-url="<?php echo $this->url(
                                   array(
                                       'module' => 'parecer',
                                       'controller' => 'analise-inicial',
                                       'action' => 'fechar-parecer'
                                   )
                               ) . $parametrosAssinatura ?>"
                           data-position="top"
                           data-delay="50"
                           data-tooltip="Concluir">
                            <i class="material-icons">check_circle</i>
                        </a>
                    <?php else : ?>
                        <a class="btn waves-effect waves-light cyan tooltipped small"
                           href="<?php echo $this->url(
                                   array(
                                       'module' => 'assinatura',
                                       'controller' => 'index',
                                       'action' => 'assinar-projeto')
                               ) . "?IdPRONAC={$this->projeto->IdPRONAC}&idTipoDoAtoAdministrativo="
                               . $this->idTipoDoAtoAdministrativo; ?>&origin=parecer/analise-inicial"
                           data-tooltip="Assinar documento"
                        >
                            <i class="material-icons white-text">create</i>
                        </a>
                    <?php endif; ?>
                <?php else : ?>
                    <a class="btn waves-effect waves-light cyan tooltipped small"
                       href="<?php echo $this->url(
                               array(
                                   'module' => 'parecer',
                                   'controller' => 'analise-inicial',
                                   'action' => 'encaminhar-assinatura')
                           ) . "?IdPRONAC={$this->projeto->IdPRONAC}&encaminhar=true&origin=parecer/analise-inicial" ?>"
                       data-tooltip="Gerar documento para assinatura">
                        <i class="material-icons white-text">note_add</i>
                    </a>
                <?php endif; ?>
            <?php else : ?>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/save.gif"
                     onclick="redirecionar('<?php echo $this->url(
                         array(
                             'module' => 'parecer',
                             'controller' => 'analise-inicial',
                             'action' => 'fechar-parecer',
                             'idPronac' => $this->projeto->IdPRONAC,
                             'idD' => $this->projeto->idDistribuirParecer,
                             'idProduto' => $this->projeto->idProduto,
                             'stPrincipal' => $this->projeto->stPrincipal
                         )
                     ); ?>')"
                     style="cursor: pointer;" title="Concluir An&aacute;lise"
                     alt="Concluir An&aacute;lise"/>
            <?php endif; ?>
        <?php endif; ?>

        <?php /* fechamento do produto secundário */ ?>
        <?php if (
            $this->projeto->stPrincipal == 0 &&
            $isProdutosPendentesParecer == 0 &&
            $this->quantidadeDiligencias == 0
        ): ?>
            <?php $parametrosAssinatura = "?idPronac=" . $this->projeto->IdPRONAC
                . "&idProduto=" . $this->projeto->idProduto
                . "&situacao=" . $this->projeto->situacao
                . "&idD=" . $this->projeto->idDistribuirParecer
                . "&stPrincipal=" . $this->projeto->stPrincipal
                . "&concluir=1";
            ?>

            <a class="btn waves-effect waves-light tooltipped small btn cyan"
               href="#modalConfirmacao"
               data-redirect-url="<?php echo $this->url(
                       array(
                           'module' => 'parecer',
                           'controller' => 'analise-inicial',
                           'action' => 'fechar-parecer'
                       )
                   ) . $parametrosAssinatura ?>"
               data-position="top"
               data-delay="50"
               data-tooltip="Concluir"
            >
                <i class="material-icons">check_circle</i>
            </a>
        <?php endif; ?>
    </div>
</div>
