<main>
    <?php
    $links = array(
        array('An&aacute;lise t&eacute;cnica inicial' => array())
    );
    ?>
    <div class="row">
        <div class="col s10">
            <?php gerarBreadCrumb($links); ?>
        </div>
    </div>
    <div class="content padding20 clearfix">
        <div class="">
            <div class="row">
                <div class="col s12 m12 l12">
                    <div  id="propostasCadastradas">
                        <table class="bordered striped conteudoImprimivel" id="tabelaAnaliseFinal">
                            <thead>
                                <tr>
                                    <th>Pronac</th>
                                    <th>Nome do Projeto</th>
                                    <th>Produto</th>
                                    <th>Produto Principal</th>
                                    <th>Data de Recebimento</th>
                                    <th>Qtde. Dias</th>
                                    <th class="center-align">Dilig&ecirc;ncia</th>
                                    <th class="center-align">Hist&oacute;rico</th>
                                    <th class="center-align">Impedimento</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s10">
                <div class="row">
                    <div class="col s2">
                        <span class="btn small white-text green"><i class="material-icons">warning</i></span> A diligenciar
                    </div>
                    <div class="col s2">
                        <span class="btn small white-text yellow"><i class="material-icons">warning</i></span> Diligenciado
                    </div>
                    <div class="col s3">
                        <span class="btn small white-text blue"><i class="material-icons">warning</i></span> Dilig&ecirc;ncia respondida
                    </div>
                    <div class="col s3">
                        <span class="btn small white-text orange"><i class="material-icons">warning</i></span> Dilig&ecirc;ncia n&atilde;o respondida
                    </div>
                </div>
            </div>
        </div>


        <?php if ($this->qtdRegistro != 0){ ?>
        <div class="row">
            <div class="col s12">

                <table class="tabela">
                    <table class="bordered margin0 dataTable">
                        <thead>
                        <th class="center-align">PRONAC</th>
                        <th class="center-align">Nome do Projeto</th>
                        <th class="center-align">Produto</th>
                        <th class="center-align">Tipo de produto</th>
                        <th class="center-align">Data de Recebimento</th>
                        <th class="center-align">Tempo Restante</th>
                        <th class="center-align">Dilig&ecirc;ncia</th>
                        <th class="center-align">Tempo da Dilig&ecirc;ncia</th>
                        <th class="center-align">Hist&oacute;rico</th>
                        <th class="center-align" width="250">Conclus&atilde;o</th>
                        <th class="center-align">Declarar impedimento</th>
                        </thead>
                        <?php
                        $rp = '';
                        $diligenciado = '';
                        $Titlediligenciado = '';

                        foreach ($this->buscar as $d) :

                            /* Verifica se tem diligencia para o projeto  */
                            $tbDiligencia = new tbDiligencia();
                            $rsDilig = $tbDiligencia->buscarDados($d->IdPRONAC);

                            // Conta quantas diligencias existe
                            $dilig = count($rsDilig);

                            $diligencia = NULL;
                            $tempoRestante = NULL;
                            $tempoDiligencia = NULL;

                            /* Diligencia */
                            if ($d->DtSolicitacao && $d->DtResposta == NULL) {
                                $diligencia = 1;
                            } else if ($d->DtSolicitacao && $d->DtResposta != NULL) {
                                $diligencia = 2;
                            } else if ($d->DtSolicitacao && round(data::CompararDatas($d->DtDistribuicao)) > $d->tempoFimDiligencia) {
                                $diligencia = 3;
                            } else {
                                $diligencia = 0;
                            }

                            switch ($diligencia) {
                                case 0:
                                    $diligenciado = "notice1.png";
                                    $Titlediligenciado = "A Diligenciar";
                                    $corDiligencia = "light-green accent-3";
                                    break;
                                case 1:
                                    $diligenciado = "notice.png";
                                    $Titlediligenciado = "Diligenciado";
                                    $corDiligencia = "yellow accent-3";
                                    break;
                                case 2:
                                    $diligenciado = "notice3.png";
                                    $Titlediligenciado = "Diligencia respondida";
                                    $corDiligencia = "cyan lighten-1";
                                    break;
                                case 3:
                                    $diligenciado = "notice2.png";
                                    $Titlediligenciado = "Diligencia n&atilde;o respondida";
                                    $corDiligencia = "amber accent-4";

                                    break;
                            }


                            /* Tempo Restante */
                            switch ($diligencia) {
                                case 0:
                                    $tempoRestante = round(data::CompararDatas($d->DtDistribuicao));
                                    break;
                                case 1:
                                    $tempoRestante = round(data::CompararDatas($d->DtDistribuicao, $d->DtSolicitacao));
                                    break;
                                case 2:
                                    $tempoRestante = round(data::CompararDatas($d->DtResposta));
                                    break;
                                case 3:
                                    $tempoRestante = round(data::CompararDatas($d->DtResposta));
                                    break;
                            }

                            /* Tempo Diligencia */
                            switch ($diligencia) {
                                case 1:
                                    $tempoDiligencia = round(data::CompararDatas($d->DtSolicitacao));
                                    break;
                            }

                            /* At&eacute; 10 dias (Verde)
                               -Entre 10 at&eacute; 20 dias (amarelo)
                               -Produto distribuido apos 20 dias (vermelho); *
                            */

                            if ($tempoRestante <= 10) {
                                $tempoCor = 'green';
                            } else if ($tempoRestante > 10 && $tempoRestante <= 20) {
                                $tempoCor = 'yellow';
                            } else {
                                $tempoCor = 'red';
                            }

                            $verificarIN2017 = $this->verificarIN2017($d->IdPRONAC);
                            $isProjetoJaAssinado = $this->IsProjetoJaAssinado($d->IdPRONAC, $this->idTipoDoAtoAdministrativo, $this->idPerfilDoAssinante);
                            $isProjetoDisponivelParaAssinatura = $this->IsProjetoDisponivelParaAssinatura($d->IdPRONAC, $this->idTipoDoAtoAdministrativo);
                            $isProdutosPendentesParecer = $this->IsProdutosPendentesParecer($d->IdPRONAC, $d->idProduto);

                            ?>
                            <tr id="produto_<?= $d->idProduto; ?>" >
                                <td class="center-align">
                                    <a class="waves-effect waves-dark btn white black-text"
                                       href="<?php echo $this->url(
                                               array(
                                                   'module' => 'default',
                                                   'controller' => 'consultardadosprojeto',
                                                   'action' => 'index'
                                               )
                                           ) . "?idPronac=" . $d->IdPRONAC; ?>"><u><?php echo $d->PRONAC; ?></u></a>
                                </td>
                                <td class="center-align">
                                    <?= $d->NomeProjeto; ?>
                                </td>
                                <td class="center-align">
                                    <?php if ($verificarIN2017): ?>
                                        <?php if (!$isProjetoJaAssinado): ?>
                                            <a href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analisarprojetoparecer', 'action' => 'produto')); ?>?idPronac=<?php echo $d->IdPRONAC; ?>&idProduto=<?php echo $d->idProduto; ?>&stPrincipal=<?php echo $d->stPrincipal; ?>&idD=<?php echo $d->idDistribuirParecer; ?>"> <?php echo $d->dsProduto; ?></a>
                                        <?php else: ?>
                                            <?php if ($d->idAgenteParecerista == $this->idAgenteParecerista): ?>
                                                <a href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analisarprojetoparecer', 'action' => 'produto')); ?>?idPronac=<?php echo $d->IdPRONAC; ?>&idProduto=<?php echo $d->idProduto; ?>&stPrincipal=<?php echo $d->stPrincipal; ?>&idD=<?php echo $d->idDistribuirParecer; ?>"> <?php echo $d->dsProduto; ?></a>
                                            <?php else: ?>
                                                <?php echo $d->dsProduto; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                    <?php else: ?>
                                        <a href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analisarprojetoparecer', 'action' => 'produto')); ?>?idPronac=<?php echo $d->IdPRONAC; ?>&idProduto=<?php echo $d->idProduto; ?>&stPrincipal=<?php echo $d->stPrincipal; ?>&idD=<?php echo $d->idDistribuirParecer; ?>"> <?php echo $d->dsProduto; ?></a>
                                    <?php endif; ?>
                                </td>
                                <td class="center-align"><?php if ($d->stPrincipal == 1): ?><img
                                        src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" width="20px"
                                        style="cursor: pointer;" title="Produto principal"
                                        alt="Produto principal" /><?php endif; ?>
                                </td>
                                <td class="center-align"><?php echo Data::tratarDataZend($d->DtDistribuicao, 'Brasileira'); ?></td>
                                <td class="center-align"><?php echo "<b style='color:" . $tempoCor . "'>" . $tempoRestante . " de 10</b>"; ?></td>
                                <td class="center-align">
                                    <?php if (!$isProjetoJaAssinado): ?>
                                        <img
                                            src="<?php echo $this->baseUrl(); ?>/public/img/<?php echo $diligenciado; ?>"
                                            title="<?php echo $Titlediligenciado; ?>" width="30px"
                                            onclick="window.open('<?php echo $this->url(array('module' => 'proposta', 'controller' => 'diligenciar', 'action' => 'listardiligenciaanalista')) ?>?idPronac=<?php echo $d->IdPRONAC ?>&idProduto=<?php echo $d->idProduto; ?>&situacao=<?php echo $d->situacao; ?>&tpDiligencia=124')"
                                            style="cursor: pointer;" alt="Diligencia"/>
                                    <?php endif; ?>
                                </td>
                                <td class="center-align"><?php echo $d->tempoFimDiligencia; ?></td>
                                <td class="center-align">
                                    <a class="btn waves-effect waves-light cyan tooltipped small"
                                       href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analisarprojetoparecer', 'action' => 'historico', 'idPronac' => $d->IdPRONAC, 'stPrincipal' => $d->stPrincipal, 'idProduto' => $d->idProduto)); ?>"
                                       data-tooltip="Hist&oacute;rico">
                                        <i class="material-icons white-text">history</i>
                                    </a>
                                </td>
                                <td class="center-align conclusao">

                                </td>
                                <td class="center-align">
                                    <?php if ($verificarIN2017): ?>
                                        <?php if (!$isProjetoDisponivelParaAssinatura):
                                            $parametrosAssinatura = "?idPronac=" . $d->IdPRONAC . "&idProduto=" . $d->idProduto . "&situacao=" . $d->situacao . "&idD=" . $d->idDistribuirParecer;
                                            ?>
                                            <a class="btn waves-effect waves-light tooltipped small btn red accent-2"
                                               href="<?php echo $this->url(
                                                       array(
                                                           'module' => 'parecer',
                                                           'controller' => 'analisarprojetoparecer',
                                                           'action' => 'devolver-parecer'
                                                       )) . $parametrosAssinatura ?>"
                                               data-position="top"
                                               data-delay="50"
                                               data-tooltip="Declarar impedimento">
                                                <i class="material-icons">highlight_off</i>
                                            </a>

                                        <?php endif; ?>
                                    <?php elseif (!$verificarIN2017): ?>
                                        <img id="img_encaminhar_parecer834782" style="cursor:pointer; "
                                             title="Declarar impedimento" src="/public/img/table_multiple.png"
                                             onclick="redirecionar('<?php echo $this->url(array('module' => 'parecer', 'controller' => 'analisarprojetoparecer', 'action' => 'devolver-parecer')) ?>?idPronac=<?php echo $d->IdPRONAC ?>&idProduto=<?php echo $d->idProduto; ?>&situacao=<?php echo $d->situacao; ?>&idD=<?php echo $d->idDistribuirParecer; ?>')">
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php
                            $rp = $d->PRONAC;
                        endforeach;
                        ?>
                    </table>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <table class="tabela">
                    <tr>
                        <td>
                            <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice1.png"
                                                           width="20px"/></div>
                            <div style="margin-top: 2px; margin-right: 15px; margin-left: 3px; float: left;"> A
                                diligenciar
                            </div>
                            <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice.png"
                                                           width="20px"/></div>
                            <div style="margin-top: 2px;  margin-right: 15px; margin-left: 3px; float: left">
                                Diligenciado
                            </div>
                            <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice3.png"
                                                           width="20px"/></div>
                            <div style="margin-top: 2px; margin-right: 15px; margin-left: 3px; float: left"> Dilig&ecirc;ncia
                                respondida
                            </div>
                            <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice2.png"
                                                           width="20px"/></div>
                            <div style="margin-top: 2px; margin-right: 15px; margin-left: 3px; float: left"> Dilig&ecirc;ncia
                                n&atilde;o respondida
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </div>


    <!-- ========== PAGINACAO========== -->
<?php if ($this->qtdRegistro > 5) {
    echo "<p>" . $this->buscar . "</p>";
} ?>
    <!-- ========== FIM PAGINACAO ========== -->

<?php } else { ?>
    <div class="row">

        <div class="col s10">Nenhum registro encontrado</div>
    </div>
<?php } ?>

    <div id="conteudoDialogoModal">

        <div id="modalConfirmacao" class="modal modal-fixed-footer">
            <div class="modal-content">
                <h4>Confirma&ccedil;&atilde;o</h4>
                <p>Tem certeza que deseja concluir a an&aacute;lise do projeto <span class="bold"
                                                                                     id="nrPronacConfirmacao"></span> ?
                </p>
            </div>
            <div class="modal-footer">
                <a href="#!" id="botaoConfirmacaoEncaminhamento"
                   class="modal-action modal-close waves-effect waves-green btn-flat">Sim</a>
                <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">N&atilde;o</a>
            </div>
        </div>

    </div>

    <script>
        $3(document).ready(function () {
            $3('.modal').modal({
                dismissible: true,
                opacity: .5,
                inDuration: 300,
                outDuration: 200,
                startingTop: '4%',
                endingTop: '10%',
                ready: function (modal, trigger) {
                    $(modal).find('#botaoConfirmacaoEncaminhamento').attr('href', $3(trigger).data('redirectUrl'));
                }
            });
            ;

            $3($3(location).attr('hash') ).each(function( index ) {
                $(this).addClass('orange lighten-3');
            });
        });
    </script>

    <br clear="all"/>
    <script
        src="https://code.jquery.com/jquery-1.12.4.js"
        integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous">
    </script>
</main>


<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
<script type="text/javascript">
    (function ($) {
        $(document).ready(function () {

            var table =  $('#tabelaAnaliseFinal').DataTable(
                {
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                    }
                    , "lengthChange": true
                    , "ajax": {
                    url: "/parecer/analise-inicial/listar-produtos-por-projeto-ajax",
                    data: {"idagente": function (d) {
                        return $('#proponente').val();
                    }},
                    type: "POST"
                },
                    "processing": true,
                    "serverSide": true,
                    "bFilter": false,
                    "aoColumnDefs": [
                        {'bSortable': false, 'aTargets': [3]},
                        {"className": "dt-center", "targets": [3,4,5,6,7,8]}
                    ],
                    "order": [[ 0, 'desc' ], [ 1, 'asc' ]],
                    "columns": [
                        {
                            data: null,
                            "name": "IdPRONAC",
                            render: function (data, type, row) {
                                return '<a class="" target="_blank" href="/default/consultardadosprojeto/index?idPronac=' + data.IdPRONAC + '">'
                                    + data.PRONAC + '</a>'
                            }
                        },
                        {
                            "name": "NomeProjeto",
                            "data": "NomeProjeto"

                        },
                        {
                            "name": "dsProduto",
                            "data": "dsProduto",
                            data: null,
                            "name": "dsProduto",
                            render: function (data, type, row) {
                                return '<a class="" href="/parecer/analise-inicial/analisar?idPronac=' + data.IdPRONAC + '&idProduto=' + data.idProduto + '&stPrincipal=' + data.stPrincipal + '&idD=' + data.idDistribuirParecer + '">'
                                    + data.dsProduto + '</a>'
                            }

                        },
                        {
                            data: null,
                            render: function ( data, type, row ) {
                                if (data.stPrincipal == 1) {
                                    return '<i class="material-icons">done</i>';
                                }
                                return '';
                            }
                        },
                        {
                            "name": "DtDistribuicao",
                            "data": "DtDistribuicao"

                        },
                        {
                            "name": "qtDias",
                            "data": "qtDias"

                        },
                        {
                            data: null,
                            name: 'stDiligencia',
                            render: function ( data, type, row ) {

                                var classe = 'green', title = 'A diligenciar';

                                if (data.stDiligencia == "diligenciado") {
                                    classe = 'yellow';
                                    title = 'Diligenciado';
                                } else if (data.stDiligencia == "diligencia_respondida") {
                                    classe = 'blue';
                                    title = 'Diligencia respondida';
                                }

                                return '<a class="waves-effect waves-dark btn small white-text ' + classe + '"' +
                                        ' title="' + title + '"' +
                                        ' href="/proposta/diligenciar/listardiligenciaanalista?' +
                                        'idPronac=' + data.IdPRONAC +
                                        '&idProduto=' + data.idProduto +
                                        '&situacao=' + data.Situacao +
                                        '&tpDiligencia=124">' +
                                        '<i class="material-icons">warning</i>' +
                                    '</a>';
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, row) {
                                return '<a class="waves-effect waves-dark btn small white-text blue"' +
                                        ' title="Historico"' +
                                        ' href="/parecer/analisarprojetoparecer/historico' +
                                        '/idPronac/' + data.IdPRONAC +
                                        '/stPrincipal/' + data.stPrincipal +
                                        '/idProduto/' + data.idProduto + '">' +
                                        '<i class="material-icons">history</i>' +
                                    '</a>';
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, row) {
                                return '<a class="waves-effect tooltipped waves-dark btn small red accent-2"' +
                                    ' data-position="top"' +
                                    ' data-delay="50"' +
                                    ' data-tooltip="Declarar impedimento"' +
                                    ' href="/parecer/analisarprojetoparecer/devolver-parecer?' +
                                    'idPronac=' + data.IdPRONAC +
                                    '&idProduto=' + data.idProduto +
                                    '&situacao=' + data.Situacao +
                                    '&idD=' + data.idDistribuirParecer + '">' +
                                    '<i class="material-icons">highlight_off</i>' +
                                    '</a>';
                            }
                        }
                    ]
                }
            );


            $("#localizar").click(function () {
                table.ajax.reload();
            });

        });
    }($.noConflict(true)));
</script>