<main>
    <?php
    $links = array(
        array('An&aacute;lise t&eacute;cnica inicial' => array())
    );
    ?>
    <div class="row">
        <div class="col s10">
            <?php gerarBreadCrumb($links); ?>
        </div>
    </div>
    <div class="content padding20 clearfix">
        <div class="">
            <div class="row">
                <div class="col s12 m12 l12">
                    <div  id="propostasCadastradas">
                        <table class="bordered striped conteudoImprimivel" id="tabelaAnaliseFinal">
                            <thead>
                                <tr>
                                    <th>Pronac</th>
                                    <th>Nome do Projeto</th>
                                    <th>Produto</th>
                                    <th>Produto Principal</th>
                                    <th>Data de Recebimento</th>
                                    <th>Qtde. Dias</th>
                                    <th class="center-align">Dilig&ecirc;ncia</th>
                                    <th class="center-align">Hist&oacute;rico</th>
                                    <th class="center-align">Impedimento</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s10">
                <div class="row">
                    <div class="col s2">
                        <span class="btn small white-text green"><i class="material-icons">warning</i></span> A diligenciar
                    </div>
                    <div class="col s2">
                        <span class="btn small white-text yellow"><i class="material-icons">warning</i></span> Diligenciado
                    </div>
                    <div class="col s3">
                        <span class="btn small white-text blue"><i class="material-icons">warning</i></span> Dilig&ecirc;ncia respondida
                    </div>
                    <div class="col s3">
                        <span class="btn small white-text orange"><i class="material-icons">warning</i></span> Dilig&ecirc;ncia n&atilde;o respondida
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="conteudoDialogoModal">

        <div id="modalConfirmacao" class="modal modal-fixed-footer">
            <div class="modal-content">
                <h4>Confirma&ccedil;&atilde;o</h4>
                <p>Tem certeza que deseja concluir a an&aacute;lise do projeto <span class="bold"
                                                                                     id="nrPronacConfirmacao"></span> ?
                </p>
            </div>
            <div class="modal-footer">
                <a href="#!" id="botaoConfirmacaoEncaminhamento"
                   class="modal-action modal-close waves-effect waves-green btn-flat">Sim</a>
                <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">N&atilde;o</a>
            </div>
        </div>
    </div>
</main>

<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
<script type="text/javascript">

    $3(document).ready(function () {
        $3('.modal').modal({
            dismissible: true,
            opacity: .5,
            inDuration: 300,
            outDuration: 200,
            startingTop: '4%',
            endingTop: '10%',
            ready: function (modal, trigger) {
                $(modal).find('#botaoConfirmacaoEncaminhamento').attr('href', $3(trigger).data('redirectUrl'));
            }
        });

        $3($3(location).attr('hash') ).each(function( index ) {
            $(this).addClass('orange lighten-3');
        });
    });

    (function ($) {
        $(document).ready(function () {

            var table =  $('#tabelaAnaliseFinal').DataTable(
                {
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                    }
                    , "lengthChange": true
                    , "ajax": {
                    url: "/parecer/analise-inicial/listar-produtos-por-projeto-ajax",
                    data: {"idagente": function (d) {
                        return $('#proponente').val();
                    }},
                    type: "POST"
                },
                    "processing": true,
                    "serverSide": true,
                    "bFilter": false,
                    "aoColumnDefs": [
                        {'bSortable': false, 'aTargets': [3]},
                        {"className": "dt-center", "targets": [3,4,5,6,7,8]}
                    ],
                    "order": [[ 0, 'desc' ], [ 1, 'asc' ]],
                    "columns": [
                        {
                            data: null,
                            "name": "IdPRONAC",
                            render: function (data, type, row) {
                                return '<a class="" target="_blank" href="/default/consultardadosprojeto/index?idPronac=' + data.IdPRONAC + '">'
                                    + data.PRONAC + '</a>'
                            }
                        },
                        {
                            "name": "NomeProjeto",
                            "data": "NomeProjeto"

                        },
                        {
                            "name": "dsProduto",
                            "data": "dsProduto",
                            data: null,
                            "name": "dsProduto",
                            render: function (data, type, row) {
                                return '<a class="" href="/parecer/analise-inicial/analisar?idPronac=' + data.IdPRONAC + '&idProduto=' + data.idProduto + '&stPrincipal=' + data.stPrincipal + '&idD=' + data.idDistribuirParecer + '">'
                                    + data.dsProduto + '</a>'
                            }

                        },
                        {
                            data: null,
                            render: function ( data, type, row ) {
                                if (data.stPrincipal == 1) {
                                    return '<i class="material-icons">done</i>';
                                }
                                return '';
                            }
                        },
                        {
                            "name": "DtDistribuicao",
                            "data": "DtDistribuicao"

                        },
                        {
                            "name": "qtDias",
                            "data": "qtDias"

                        },
                        {
                            data: null,
                            name: 'stDiligencia',
                            render: function ( data, type, row ) {

                                var classe = 'green', title = 'A diligenciar';

                                if (data.stDiligencia == "diligenciado") {
                                    classe = 'yellow';
                                    title = 'Diligenciado';
                                } else if (data.stDiligencia == "diligencia_respondida") {
                                    classe = 'blue';
                                    title = 'Diligencia respondida';
                                }

                                return '<a class="waves-effect waves-dark btn small white-text ' + classe + '"' +
                                        ' title="' + title + '"' +
                                        ' href="/proposta/diligenciar/listardiligenciaanalista?' +
                                        'idPronac=' + data.IdPRONAC +
                                        '&idProduto=' + data.idProduto +
                                        '&situacao=' + data.Situacao +
                                        '&tpDiligencia=124">' +
                                        '<i class="material-icons">warning</i>' +
                                    '</a>';
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, row) {
                                return '<a class="waves-effect waves-dark btn small white-text blue"' +
                                        ' title="Historico"' +
                                        ' href="/parecer/analisarprojetoparecer/historico' +
                                        '/idPronac/' + data.IdPRONAC +
                                        '/stPrincipal/' + data.stPrincipal +
                                        '/idProduto/' + data.idProduto + '">' +
                                        '<i class="material-icons">history</i>' +
                                    '</a>';
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, row) {
                                return '<a class="waves-effect tooltipped waves-dark btn small red accent-2"' +
                                    ' data-position="top"' +
                                    ' data-delay="50"' +
                                    ' data-tooltip="Declarar impedimento"' +
                                    ' href="/parecer/analisarprojetoparecer/devolver-parecer?' +
                                    'idPronac=' + data.IdPRONAC +
                                    '&idProduto=' + data.idProduto +
                                    '&situacao=' + data.Situacao +
                                    '&idD=' + data.idDistribuirParecer + '">' +
                                    '<i class="material-icons">highlight_off</i>' +
                                    '</a>';
                            }
                        }
                    ]
                }
            );

            $("#localizar").click(function () {
                table.ajax.reload();
            });

        });
    }($.noConflict(true)));
</script>