<div id="menu-suspenso" class="fixed-action-btn vertical click-to-toggle">
    <a id="bt-aciona-menu" class="btn-floating btn-large red"><i class="large material-icons">add</i></a>
    <ul>
        <li>
            <a id="ir-para-o-topo" class="btn-floating yellow darken-1 tooltipped" data-tooltip="Ir para o topo">
                <i class="material-icons">navigation</i>
            </a>
        </li>
        <li>
            <a
                class="btn-floating blue tooltipped waves-effect waves-light modal-trigger"
                data-tooltip="An&aacute;lise de Conte&uacute;do"
                href="#analisar-conteudo">
                <i class="material-icons">playlist_add_check</i>
            </a>
        </li>
        <li>
            <a
                id="bt-analisar-custos"
                href="javascript:void(0)"
                class="btn-floating blue tooltipped"
                data-tooltip="Análise de custo">
                <i class="material-icons">attach_money</i>
            </a>
        </li>
        <li>
            <a
                class="btn-floating blue tooltipped waves-effect waves-light modal-trigger"
                data-tooltip="Consolidar parecer t&eacute;cnico"
                href="#consolidar-parecer-tecnico">
                <i class="material-icons">gavel</i>
            </a>
        </li>
    </ul>
</div>

<script>
    $3(document).ready(function ($) {

        $("#visualizar-form").on('click', function () {
            tinymce.remove();
        });

        $("#bt-analisar-custos").on('click', function() {
            $('ul.tabs').tabs('select_tab', 'tab_analise_custo');
        });

        if ($('#ir-para-o-topo').length) {
            var scrollTrigger = 100, // px
                backToTop = function () {
                    var scrollTop = $(window).scrollTop();
                    if (scrollTop > scrollTrigger) {
                        $('#ir-para-o-topo').parent().show();
                    } else {
                        $('#ir-para-o-topo').parent().hide();
                    }
                };
            backToTop();

            $(window).on('scroll', function () {
                backToTop();
            });

            $('#ir-para-o-topo').on('click', function (e) {
                e.preventDefault();
                $('html,body').animate({
                    scrollTop: 0
                }, 700);
            });
        }
    });
</script>