<?php if (count($this->produtosSecundarios)) : ?>
    <table class="bordered" id="produtosSecundarios">
        <tr>
            <th align="left">Produto</th>
            <th align="right">Tipo</th>
            <th align="right">Situa&ccedil;&atilde;o</th>
        </tr>
        <?php foreach ($this->produtosSecundarios as $ps) : ?>
            <tr>
                <td class="" align="left">
                    <a target="_blank"
                       href="<?= $this->url(array('module' => 'parecer', 'controller' => 'analise-inicial', 'action' => 'analisar-produto-do-projeto')); ?>?idPronac=<?= $ps['IdPRONAC']; ?>&idProduto=<?= $ps['idProduto']; ?>&stPrincipal=<?= $ps['stPrincipal']; ?>">
                        <?= $ps['Produto']; ?>
                    </a>
                </td>
                <td>
                    <div>
                        <?= $ps['DescricaoAnalise']; ?>
                    </div>
                </td>
                <td>
                    <div>
                        <?= $ps['Situacao']; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else : ?>
    <div>
        <div class="center-align">N&atilde;o h&aacute; produto secund&aacute;rio.</div>
    </div>
<?php endif; ?>
