<style>
    .bordered-all td {
        border: solid 1px #c9c9c9 !important;
    }
</style>
<div class="row">
    <form id="form-mensagem" class="materialize" data-ajax-form="true" method="post"
          action="<?php echo $this->urlAction ?>">
        <div class="modal-content">
            <div class="row">
                <div class="col s1"></div>
                <div class="col s10 center-align">
                    <div>
                        <img src="/public/img/planalto_presidencia_simbolosnacionais_brasao.gif" style="height:120px">
                    </div>
                    <div class="center-align" style="font-size: 23px;">
                        MINIST&Eacute;RIO DA CULTURA
                    </div>
                    <div class="center-align" style="font-size: 23px;">
                        <b>SECRETARIA DE FOMENTO E INCENTIVO &Agrave; CULTURA</b>
                    </div>
                </div>
                <div class="col s1"></div>
            </div>
<!--            <h4>Gerar documento e encaminhar</h4>-->
            <div>
                <ul class="collapsible popout" data-collapsible="expandable">
                    <?php echo $this->partial('/homologacao/partials/visualizar.phtml', ['arrValue' => $this->arrValue, 'booShowAll' => true]); ?>
                </ul>
            </div>

            <div>
                <table class="bordered-all" style="width: 100%;">
                    <tbody>
                        <tr><td colspan="3">Assinado eletronicamente conforme estabelecido no artigo 132 da Instru&ccedil;&atilde;o Normativa n&ordm; 1 de 2017.</td></tr>
                        <tr>
                            <td class="center">Nome</td>
                            <td class="center">Cargo</td>
                            <td class="center">Dt.Assinatura</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="center"><b>Coordenador-Geral</b></td>
                            <td class="center"></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="center"><b>Diretor</b></td>
                            <td class="center"></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="center"><b>Secret&aacute;rio</b></td>
                            <td class="center"></td>
                        </tr>
                    </tbody>

                </table>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn waves-effect waves-light" type="submit" name="action">Gerar e Encaminhar</button>
            <a href="#!" class="modal-action modal-close waves-effect waves-orange btn-flat orange-text" style="margin-right: 15px;">Fechar</a>
        </div>
    </form>
</div>

<script>
    $3('.collapsible').collapsible();
</script>