<style>
    .bordered-all td {
        border: solid 1px #c9c9c9 !important;
    }
</style>

<form id="form-mensagem" class="materialize" data-ajax-form="true" method="post"
      action="<?php echo $this->urlAction ?>">
    <div class="modal-content">
        <h4>Gerar documento e encaminhar</h4>
        <div>
            <ul class="collapsible popout" data-collapsible="accordion">
                <?php echo $this->partial('/homologacao/partials/visualizar.phtml', ['arrValue' => $this->arrValue]); ?>
            </ul>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn waves-effect waves-light" type="submit" name="action">Encaminhar</button>
        <a href="#!" class="modal-action modal-close waves-effect waves-orange btn-flat orange-text" style="margin-right: 15px;">Fechar</a>
    </div>
</form>
<script>
    $3('.collapsible').collapsible();
</script>