<div class="container-fluid">
    <section class="row">
        <article class="col s12">
            <h2>Prestação de Contas: Avaliação por Amostragem</h2>
        </article>
    </section>
    <section class="row">
        <article id="vue-container" class="col s12">
            <salic-projeto-identificacao idPronac="<?php echo ($this->idPronac);?>" ></salic-projeto-identificacao>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Avaliação Financeira por Amostragem</span>
                    <div class="row">
                        <div class="col l12 s12">
                            <table class="bordered">
                            <thead>
                                <tr>
                                    <th rowspan="2">Item</th>
                                    <th rowspan="2">Fornecedor</th>
                                    <th colspan="5">Pagamento</th>
                                    <th rowspan="2">Estado</th>
                                </tr>
                                <tr>
                                    <th>Data<th>
                                    <th>Forma</th>
                                    <th>Número</th>
                                    <th>Valor</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                </tr>
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>
</div>

<script src="/public/js/vue.js" type="text/javascript"></script>

<script id="salic-projeto-identificacao" type="text/javascript">
    <div class="card">
        <div class="card-content">
            <span class="card-title">Identificação Projeto</span>
            <div class="row">
                <div class="col l2 s12">
                   PRONAC: <strong>{{dados.PRONAC}}</strong>
                </div>
                <div class="col l2 s12">
                   Projeto: <strong>{{dados.nome}}</strong>
                </div>
                <div class="col  l2 s12">
                   Segmento:
                    <strong>{{dados.descricao}}</strong>
                </div>
                <div class="col  l2 s12">
                   Proponente:
                    <strong>{{dados.nomeAgente}}</strong>
                </div>
                <div class="col  l3 s12">
                   Situação: 
                    <strong>{{dados.situacao}}</strong>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/javascript">
    Vue.component('salic-projeto-identificacao', {
        template: '#salic-projeto-identificacao',
        data: function() {
            return {
                dados:[]
            }
        },
        props: ['idpronac', 'pronac'],
        mounted: function() {
            this.fetch(this.idpronac);
        },
        computed:{
        },
        methods: {
            fetch: function(idpronac) {

                let vue = this;
                $3.ajax({
                    url: '/projeto/projeto/identificacao?idPronac=' + idpronac
                })
                .done( function(data) {
                    vue.dados = data;
                });
            }
        }
    });

    var app = new Vue({
        el: '#vue-container'
    });
</script>
