<div class="container-fluid">
    <section class="row">
        <article class="col s12">
            <h2>Presta&ccedil;&atilde;o de Contas: Avalia&ccedil;&atilde;o por Amostragem</h2>
        </article>
    </section>
    <section class="row">
        <article id="vue-container" class="col s12">
            <salic-projeto-identificacao idPronac="<?php echo ($this->idPronac);?>"></salic-projeto-identificacao>
        </article>
        <article class="col s12">
            <div class="card z-depth-2">
                <div class="card-content">
                    <span class="card-title">Avalia&ccedil;&atilde;o Financeira por Amostragem</span>
                    <div class="row">
                        <div class="col l12 s12">
                          <ul class="collapsible popout " data-collapsible="accordion">
                            <?php foreach($this->comprovantes as $comprovante):?>
                              <li class="">
                                <div 
                                  class="collapsible-header  waves-effect
                                    <?php if($comprovante->stEstado[0] == "S") : ?> 
                                      grey lighten-2 
                                    <?php elseif($comprovante->stEstado[0] == "V") : ?> 
                                      green lighten-3
                                    <?php elseif($comprovante->stEstado[0] == "I") : ?> 
                                      red lighten-3
                                    <?php endif ?> "
                                  >
                                    <?php if($comprovante->stEstado[0] == "S") : ?> 
                                      <i class="material-icons">check_box_outline_blank</i>
                                    <?php elseif($comprovante->stEstado[0] == "V") : ?> 
                                      <i class="material-icons">check_circle</i>
                                    <?php elseif($comprovante->stEstado[0] == "I") : ?> 
                                      <i class="material-icons">block</i>
                                    <?php endif ?> 
                                  <?php echo ($comprovante->Item) ?> - <?php echo ($comprovante->Fornecedor)?> - <?php echo number_format($comprovante->vlPagamento, 2, ',','.')?>
                                </div>
                                <div class="collapsible-body  z-depth-2">
                                      <div class="row">
                                          <div class="input-field col s12">
                                            <table class="bordered">
                                              <thead class="grey lighten-2">
                                                <tr>
                                                  <th rowspan="2">Item</th>
                                                  <th rowspan="2">Fornecedor</th>
                                                  <th class="center-align" colspan="4">Pagamento</th>
                                                  <th class="center-align" rowspan="2">Estado</th>
                                                </tr>
                                                <tr>
                                                  <th>Data</th>
                                                  <th>Forma</th>
                                                  <th>N&uacute;mero</th>
                                                  <th>Valor</th>
                                                </tr>
                                              </thead>
                                              <tbody>
                                                <tr>
                                                  <td>
                                                    <?php echo ($comprovante->Item) ?>
                                                  </td>
                                                  <td>
                                                    <?php echo ($comprovante->Fornecedor)?>
                                                  </td>
                                                  <td>
                                                    <?php echo (new DateTime($comprovante->DtComprovacao))->format('d/m/Y') ?>
                                                  </td>
                                                  <td>
                                                    <?php echo ($comprovante->tpFormaDePagamento)?>
                                                  </td>
                                                  <td>
                                                    <?php echo ($comprovante->nrDocumentoDePagamento)?>
                                                  </td>
                                                  <td>
                                                    <?php echo number_format($comprovante->vlPagamento, 2, ',', '.')?>
                                                  </td>
                                                  <td class="center-align">
                                                    <?php echo ($comprovante->stEstado)?>
                                                  </td>
                                                </tr>
                                                <tr>
                                                  <th class=" grey lighten-2">
                                                    Jutificativa do Proponente
                                                  </th>
                                                  <td colspan="7" class="">
                                                    <?php echo $comprovante->dsJustificativa ?>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div>
                                      </div>
                                      <div class="row">
                                        <div class="col l12 s12">
                                          <form action="/prestacao-contas/prestacao-contas/salvar-analise" method="post">
                                            <input name="idComprovantePagamento" type="hidden" value="<?php echo $comprovante->idComprovantePagamento ?>" >
                                            <input name="idPronac" type="hidden" value="<?php echo $this->idPronac;?>" >
                                            <fieldset>
                                              <legend>Avalia&ccedil;&atilde;o</legend>
                                              <div class="row">
                                                <div class="input-field col s12">
                                                  <textarea name="justificativa" id="ocorrencia" class="materialize-textarea"><?php echo $comprovante->ocorrenciaTecnico ?></textarea>
                                                  <label for="ocorrencia">Ocorr&ecirc;ncia:</label>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="col s12">
                                                  <strong>Avalia&ccedil;&atilde;o:</strong>
                                                  <input 
                                                  <?php if($comprovante->stEstadoId == 1):?>
                                                  checked="checked" 
                                                  <?php endif?>
                                                  name="situacao" type="radio" id="test1<?php echo $comprovante->idComprovantePagamento ?>" value="1"/>
                                                <label for="test1<?php echo $comprovante->idComprovantePagamento ?>">Comprova&ccedil;&atilde;o validada</label>
                                                <input 
                                                <?php if($comprovante->stEstadoId == 3):?>
                                                checked="checked" 
                                                <?php endif?>
                                                name="situacao" type="radio" id="test2<?php echo $comprovante->idComprovantePagamento ?>" value="3"/>
                                              <label for="test2<?php echo $comprovante->idComprovantePagamento ?>">Comprova&ccedil;&atilde;o recusada</label>
                                            </div>
                                          </div>
                                          <div class="row">
                                            <div class="center-align col s12">
                                              <button class="btn waves-effect" type="submit">salvar</button>
                                            </div>
                                          </div>
                                        </fieldset>
                                      </form>
                                    </div>
                                  </li>
                                  <?php endforeach ?>
                                </ul>
                         <!--table class="bordered">
                            <thead>
                                <tr>
                                    <th rowspan="2">Item</th>
                                    <th rowspan="2">Fornecedor</th>
                                    <th class="center-align" colspan="4">Pagamento</th>
                                    <th class="" rowspan="2">1Estado</th>
                                </tr>
                                <tr>
                                    <th>Data</th>
                                    <th>Forma</th>
                                    <th>N&uacute;mero</th>
                                    <th>Valor</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->comprovantes as $comprovante):?>
                                    <tr>
                                        <td>
                                            <?php echo ($comprovante->Item) ?>
                                        </td>
                                        <td>
                                            <?php echo ($comprovante->Fornecedor)?>
                                        </td>
                                        <td>
                                            <?php echo ($comprovante->DtComprovacao)?>
                                        </td>
                                        <td>
                                            <?php echo ($comprovante->tpFormaDePagamento)?>
                                        </td>
                                        <td>
                                            <?php echo ($comprovante->nrDocumentoDePagamento)?>
                                        </td>
                                        <td>
                                            <?php echo ($comprovante->vlPagamento)?>
                                        </td>
                                        <td class="center-align" >
                                            <?php echo ($comprovante->stEstado)?>
                                        </td>
                                    </tr>
                                <?php endforeach?>
                            </tbody>
                            </table-->
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </article>
    </section>
</div>
<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="/public/scripts/projeto/salic-projeto-identificacao.vue.js" type="text/javascript"></script>
<script type="text/javascript">
    var app = new Vue({
        el: '#vue-container'
    });
</script>
