<div class="container-fluid">
    <section class="row">
        <article class="col s12">
            <h2>Prestação de Contas: Tipo de Avaliação</h2>
        </article>
    </section>
    <section class="row">
        <article id="vue-container" class="col s12">
            <salic-projeto-identificacao idPronac="<?php echo ($this->idPronac);?>" ></salic-projeto-identificacao>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Informações sobre a avaliação de objeto</span>
                    <div class="row">
                        <div class="col l12 s12">
                            <table class="bordered">
                            <thead>
                                <tr>
                                    <th rowspan="2">Dt.Envio Prestação de Contas</th>
                                    <th rowspan="2">Resultado  da Avaliação do Objeto</th>
                                    <th colspan="3">Empregos Gerados</th>
                                </tr>
                                <tr>
                                    <th>Direto<th>
                                    <th>Indireto</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                </tr>
                            </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Informações sobre a avaliação financeira </span>
                    <div class="row">
                        <div class="col l12 s12">
                            <table class="bordered">
                              <thead>
                                  <tr>
                                      <th colspan="4">Valores</th>
                                      <th colspan="3">Quantidade de Comprovantes por nível de confiança</th>
                                  </tr>
                                  <tr>
                                      <th>Aprovado<th>
                                      <th>Captado</th>
                                      <th>Comprovado</th>
                                      <th>Todos</th>
                                      <th>95%</th>
                                      <th>90%</th>
                                      <th>99%</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  <tr>
                                      <td>
                                          25.296.427,87
                                      </td>
                                      <td>
                                          14.730.000,00
                                      </td>
                                      <td>
                                          14.931.639.68
                                      </td>
                                      <td>
                                          6.074
                                      </td>
                                      <td>
                                          259
                                      </td>
                                      <td>
                                          361
                                      </td>
                                      <td>
                                        598
                                      </td>
                                      <td>
                                        598
                                      </td>
                                  </tr>
                              </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                  <form>
                    <fieldset>
                      <legend>Selecionar o tipo de avaliação financeria</legend>
                      <p>Avaliar comprovantes  por nível de confiança:<p>
                      <p>
                        <input name="group1" type="radio" id="todos" />
                        <label for="todos">Todos comprovantes</label>
                      </p>
                      <p>
                        <input name="group1" type="radio" id="90" />
                        <label for="90">90%</label>
                      </p>
                      <p>
                        <input name="group1" type="radio" id="95" />
                        <label for="95">95%</label>
                      </p>
                      <p>
                        <input name="group1" type="radio" id="99" />
                        <label for="99">99%</label>
                      </p>
                      <button class="btn">
                          Avaliar
                      </button>
                    </fieldset>
                  <form>
                  </div>
                </div>
        </article>
    </section>
</div>

<script src="/public/js/vue.js" type="text/javascript"></script>

<script id="salic-projeto-identificacao" type="text/javascript">
    <div class="card">
        <div class="card-content">
            <span class="card-title">Identificação Projeto</span>
            <div class="row">
                <div class="col l2 s12">
                   PRONAC: <strong>{{dados.PRONAC}}</strong>
                </div>
                <div class="col l2 s12">
                   Projeto: <strong>{{dados.nome}}</strong>
                </div>
                <div class="col  l2 s12">
                   Segmento:
                    <strong>{{dados.descricao}}</strong>
                </div>
                <div class="col  l2 s12">
                   Proponente:
                    <strong>{{dados.nomeAgente}}</strong>
                </div>
                <div class="col  l3 s12">
                   Situação: 
                    <strong>{{dados.situacao}}</strong>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/javascript">
    Vue.component('salic-projeto-identificacao', {
        template: '#salic-projeto-identificacao',
        data: function() {
            return {
                dados:[]
            }
        },
        props: ['idpronac', 'pronac'],
        mounted: function() {
            this.fetch(this.idpronac);
        },
        computed:{
        },
        methods: {
            fetch: function(idpronac) {

                let vue = this;
                $3.ajax({
                    url: '/projeto/projeto/identificacao?idPronac=' + idpronac
                })
                .done( function(data) {
                    vue.dados = data;
                });
            }
        }
    });

    var app = new Vue({
        el: '#vue-container'
    });
</script>
