<div class="container-fluid">
    <section class="row">
        <article class="col s12">
            <h2>Presta&ccedil;&atilde;o de Contas: Tipo de Avalia&ccedil;&atilde;o</h2>
        </article>
    </section>
    <section class="row">
        <article id="vue-container" class="col s12">
            <salic-projeto-identificacao idPronac="<?php echo ($this->idPronac);?>" ></salic-projeto-identificacao>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Informa&ccedil;&otilde;es sobre a avalia&ccedil;&atilde;o de objeto</span>
                    <div class="row">
                        <div class="col l12 s12">
                            <table class="bordered">
                            <thead>
                                <tr>
                                    <th rowspan="2">Dt.Envio Presta&ccedil;&atilde;o de Contas</th>
                                    <th rowspan="2">Resultado  da Avalia&ccedil;&atilde;o do Objeto</th>
                                    <th class="center-align" colspan="3">Empregos Gerados</th>
                                </tr>
                                <tr>
                                    <th>Direto<th>
                                    <th>Indireto</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                    <td>
                                        teste
                                    </td>
                                </tr>
                            </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Informa&ccedil;&otilde;es sobre a avalia&ccedil;&atilde;o financeira </span>
                    <div class="row">
                        <div class="col l12 s12">
                            <table class="bordered">
                              <thead>
                                  <tr>
                                      <th colspan="4">Valores</th>
                                      <th colspan="3">Quantidade de Comprovantes por n&iacute;vel de confian&ccedil;a</th>
                                  </tr>
                                  <tr>
                                      <th>Aprovado<th>
                                      <th>Captado</th>
                                      <th>Comprovado</th>
                                      <th>Todos</th>
                                      <th>95%</th>
                                      <th>90%</th>
                                      <th>99%</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  <tr>
                                      <td>
                                          25.296.427,87
                                      </td>
                                      <td>
                                          14.730.000,00
                                      </td>
                                      <td>
                                          14.931.639.68
                                      </td>
                                      <td>
                                          6.074
                                      </td>
                                      <td>
                                          259
                                      </td>
                                      <td>
                                          361
                                      </td>
                                      <td>
                                        598
                                      </td>
                                      <td>
                                        598
                                      </td>
                                  </tr>
                              </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </article>
        <article class="col s12">
            <div class="card">
                <div class="card-content">
                  <form action="/prestacao-contas/prestacao-contas/tipo-avaliacao-salvar">
                    <input type="hidden" name="idPronac" value="<?php echo ($this->idPronac);?>">
                    <fieldset>
                      <legend>Selecionar o tipo de avalia&ccedil;&atilde;o financeria</legend>
                      <p>Avaliar comprovantes  por n&iacute;vel de confian&ccedil;a:<p>
                      <p>
                        <input name="avaliacao" type="radio" id="todos" value="todos"/>
                        <label for="todos">Todos comprovantes</label>
                      </p>
                      <p>
                        <input name="avaliacao" type="radio" id="90"  value="90"/>
                        <label for="90">90%</label>
                      </p>
                      <p>
                        <input name="avaliacao" type="radio" id="95"  value="todos"/>
                        <label for="95">95%</label>
                      </p>
                      <p>
                        <input name="avaliacao" type="radio" id="99"  value="todos"/>
                        <label for="99">99%</label>
                      </p>
                      <button class="btn">
                          Avaliar
                      </button>
                    </fieldset>
                  <form>
                  </div>
                </div>
        </article>
    </section>
</div>
<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="/public/scripts/projeto/salic-projeto-identificacao.vue.js" type="text/javascript"></script>
<script type="text/javascript">
    var app = new Vue({
        el: '#vue-container'
    });
</script>
