<div id="divAnaliseCusto">
    <table class="bordered">
        <tr>
            <th colspan="13">Planilha de Or&ccedil;amento Sugerido <input id="valorpossivel" value="<?php echo $this->valorpossivel;?>" type="hidden"/></th>
        </tr>
        <?php
            $nrfonte = 0;
            $item = 1;
            //ForeachFonteIncentivo
            foreach ($this->itens['fonte'] as $fonte => $arrayProdutos) {
        ?>
            <tr>
                <td colspan="11">
                    <div tipo="fonte" fonte="<?php echo $nrfonte; ?>" aberto="true" class="icn_menos" style="width:90%"><span class="red-text del_link" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
                </td>
            </tr>
            <?php
                $nrproduto = 0;
                foreach ($arrayProdutos as $produto => $arrayEtapas) {
            ?>
            <tr class='master' fonte="<?php echo $nrfonte; ?>">
                <td class='master' colspan="11">
                    <div  tipo="produto" aberto="true" fonte="<?php echo $nrfonte; ?>" produto ="<?php echo $nrproduto; ?>" class="icn_menos clickproduto" style="width:98%; margin-left:2%;"><span class="green-text del_link" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
                </td>
            </tr>
            <?php
                $nretapa = 0;
                foreach ($arrayEtapas as $etapa => $arrayCidades) {
            ?>
            <tr class="master produto" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>" >
                <td colspan="11">
                    <div tipo="etapa" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:4%;"><span class="orange-text del_link" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div>
                </td>
            </tr>
            <?php
                $nrcidade = 0;
                foreach ($arrayCidades as $cidade => $planilha) {
            ?>
            <tr class="master produto etapa" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" >
                <td colspan="11">
                    <div tipo="cidade" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:6%;">
                        <span class="black-text del_link" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span>
                    </div>
                </td>
            </tr>
        <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" cidade="<?php echo $nrcidade; ?>">
            <td colspan="11">
                <table class="bordered">
                    <?php
                        /* INICIO PLANILHA DE ITENS */
                        $primeiro = 0;
                        foreach ($planilha['itens'] as $idPlanilhaProjeto => $valPlanilha) {
                            $valorprodutosolicitado = 0;
                            $valorprodutoparecerista = 0;
                            $estiloCustoPraticado = ($valPlanilha['Custo praticado'] == 0) ? '' : 'valor_maior_que_praticado';

                            $trCampo = "<tr>";
                            $conteudo = "<tr class='item $estiloCustoPraticado' idPlanilhaProjeto='{$idPlanilhaProjeto}' id='item{$idPlanilhaProjeto}'>";
                            unset($valPlanilha['Custo praticado']);

                            foreach ($valPlanilha as $camp => $cont) {
                                $trCampo .= "<th>{$camp}</th>";
                                if ($camp == 'Valor Unitário' || $camp == 'Valor Solicitado' || $camp == 'Valor Sugerido pelo Parecerista') {
                                    if ($camp == 'Valor Sugerido pelo Parecerista') {
                                        $conteudo .= "<td class='ValorSugerido right-align'>{$this->formatarReal($cont)}</td>";
                                    }
                                    else {
                                        $conteudo .= "<td class='right-align'>{$this->formatarReal($cont)}</td>";
                                    }
                                }
                                else {
                                    if ($camp == 'Justificativas do Parecerista') {
                                        $conteudo .= "<td class='JustParecerista'>{$cont}</td>";
                                    }
                                    else {
                                        $conteudo .= "<td>{$cont}</td>";
                                    }
                                }
                            }
                            $trCampo .= "</tr>";
                            $conteudo .= "</tr>";

                            if ($primeiro == 0) {
                                echo $trCampo;
                            }

                            echo $conteudo;
                            $primeiro++;
                        }
                    ?>
                    <tr style="font-weight: bold;">
                        <td class="left-align black-text" style="font-size: 12pt; " colspan="7">Total de UF</td>
                        <td class="right-align black-text" style="font-size: 12pt; "><?php echo $planilha['totalUfSolicitado']; ?></td>
                        <td class="right-align black-text" style="font-size: 12pt;">&nbsp;</td>
                        <td class="valorUfSugerido  right-align" style="font-size: 12pt; width: 15%;"><?php echo $planilha['totalUfSugerido']; ?></td>
                        <td class="left-align black-text" style="font-size: 12pt; width: 12%;">&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
                        <?php
                        /* FIM PLANILHA DE ITENS */
                    }
                    $nretapa++;
                } //fechaForeachetapa
                $nrproduto++;
            } //fechaForeachproduto
            $nrfonte++;
        }//fechaForeachFonteIncentivo
        ?>
        <tr>
            <td colspan="11">
                <table class="bordered">
                    <thead>
                        <th colspan="5">Total Solicitado do produto - Todas as fontes de incentivo</th>
                        <th colspan="6">Total Sugerido do produto - Todas as fontes de incentivo</th>
                    </thead>
                    <tr>
                        <td class="centro black-text" style="font-size: 12pt; width: 12%; font-weight: bold;" colspan="5"><?php echo $this->itens['totalSolicitado']; ?></td>
                        <td class="centro valorTotalSugerido esquerda black-text" style="font-size: 12pt; width: 12%; font-weight: bold;" colspan="6"><?php echo $this->itens['totalSugerido']; ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
